### ISSUE TITLE
建议快捷键不要全局响应，

### ISSUE THREAD

**Issue by ianlie** [Hunlongyu/ZY-Player#100]
快捷键全局响应，这个功能目前对我来说算是一个问题，
因为我日常会看着视频用wps做工作，做报表，其中ctrl+方向键是常用的一个功能，
但是开了zy后，这个组合键会被zy全局响应，
导致我既不能正常使用组合键工作，又会不小心让zy跳集，相信其他人应该也会有类似的体验，
所以建议是，能选择是否全局响应，
或者能自定义组合键，让用户自己编辑避免冲突，这样既能保持全局响应，又不会与现有的冲突，

**Comment by Hunlongyu** [comment]
反馈已收到, 下一个版本修复.
最近忙于加班, 无暇更新软件.

**Comment by Hunlongyu** [comment]
最新正式版: v2.x 已发布, 欢迎体验.

新版快捷键,可以自定义了哦
