### ISSUE TITLE
选集上似乎有问题，会错集，

### ISSUE THREAD

**Issue by ianlie** [Hunlongyu/ZY-Player#102]
例如我今天打开的一个动漫，选择第三集，可是播放的是第一集，
然后再点第一集，播放的好像是第二集还是第三集，再点第四集，反正播放的也不是第四集，
一开始以为是源的问题，就换了个资源网试，也是有类似问题出现，
再进去那个资源网，试看同一个动漫，发现资源网的顺序是没错的，
所以猜测会不会是软件拉取后，在选集上有什么问题，

**Comment by FreeGAV** [comment]
这个问题好几个版本了，1.0.30反馈过，貌似是从增加播放记录时候开始存在的问题。

**Comment by linandoo** [comment]
更新到1.0.16版本之后就好了
