### ISSUE TITLE
安装显示终止

### ISSUE THREAD

**Issue by JKing9527** [Hunlongyu/ZY-Player#104]
直接蓝奏云下载的文件 安装到E盘中安装一半显示终止 怎么解决呢

**Comment by Hunlongyu** [comment]
1. 请检查不要安装在含有中文路径的文件夹下
2. 请从 github 上, 下载最新的软件包, 蓝奏云不是最新版
3. 不修改安装路径, 一路默认.

**Comment by tempso** [comment]
github上一样，显示安装中止，以上3点都已确认没问题。
win7，64位。

**Comment by Hunlongyu** [comment]
清理注册表 试一试

**Comment by jinlintansjtu** [comment]
我遇到的问题是无法安装成功

**Comment by Confucianism** [comment]
安装已中止咋解决啊，上面的方法都试了

**Comment by Hunlongyu** [comment]
最新正式版: v2.x 已发布, 欢迎体验.
