### ISSUE TITLE
🚄🚅 新版本开发预告 🚒🚚

### ISSUE THREAD

**Issue by Hunlongyu** [Hunlongyu/ZY-Player#109]
### 全新版本,从心出发

新版本开发计划已写好, 由于功能很多,且还有其他平台, 个人精力终归有限, 所以招募小伙伴, 一起完成这个项目.

主要招募: 移动端(IOS, Android), 以及TV端(Android)

我会提供接口, 接口文档, 桌面端与移动端交互说明

欢迎各路大神参与开发维护项目. 也欢迎吃瓜群众入群尝鲜测试, 提出建议.

由于精力有限, 除重大安全隐患, 旧版本不再更新功能.

开发交流群: 
<p>
<img width="256" src="https://i.loli.net/2020/06/30/WACzifl8Lb5ZVck.jpg" >
</p>

| 库 | 作者 | 平台 |
| :--- | :--- | :---: |
| https://github.com/vicedev/ZY-Player-Android | vicedev | Android |
| https://github.com/saysea/ZY-Player-Android | saysea | Android |

有其他小伙伴做的可以留言

**Comment by why2785** [comment]
刚看到，群过期了，可以拉下吗，hank5g

**Comment by Hunlongyu** [comment]
> 刚看到，群过期了，可以拉下吗，hank5g

更新了二维码

**Comment by xiaojia21190** [comment]
flutter 版本的  [https://github.com/xiaojia21190/ZY_Player_flutter](url)

**Comment by flymouse** [comment]
群需要邀请才能进
