### ISSUE TITLE
快捷键冲突？？

### ISSUE THREAD

**Issue by xiangyuanStar** [Hunlongyu/ZY-Player#110]
mac版，启动后，Mac的组合快捷键 command + 左、右方向键，不能移动光标到行头或者行的末尾了，找了好久这个问题，最近更新了系统，还以为是系统的bug

**Comment by Hunlongyu** [comment]
新版本开发中, 旧版本不再更新.

**Comment by Hunlongyu** [comment]
尝试最新内测版
