### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by wangmoi** [Hunlongyu/ZY-Player#112]
大佬你好 我是一枚新手开发者 去年由于公司业务原因也接触过electron来做桌面端开发 当时用的是electron-vue脚手架去搭建的项目 在github看到简介说支持三端就想是不是electron 点进来一看果然是 好奇之下抱着学习的想法下载了源码 发现好像和我之前的项目目录有较大出入 想请教一下我记得electron有渲染进程和主进程 electron-vue的项目目录里是并行存在于src目录下 在本项目里好像只看到了渲染进程的页面 请问主进程在哪块呢

**Comment by Hunlongyu** [comment]
你使用的应该是 Electron-vue. 
我使用的是: https://nklayman.github.io/vue-cli-plugin-electron-builder/
主进程是 background.js
可以进微信群, 或者加我微信好友 一起学习进步哦~
