### ISSUE TITLE
建议可以整合github gist的api

### ISSUE THREAD

**Issue by hooray** [Hunlongyu/ZY-Player#121]
类似vscode里的sync setting扩展，将配置信息存到gist，方便多端同步配置，也可以把收藏信息进行同步

**Comment by lemonkiller** [comment]
是的 多设备能同步就很好用

**Comment by Hunlongyu** [comment]
确实是好想法, 但我这边没有精力维护这个项目了. 最新版已发布. 不过没有添加同步功能.
