### ISSUE TITLE
资源分类+窗口+播放

### ISSUE THREAD

**Issue by X4388062** [Hunlongyu/ZY-Player#122]
资源按分类搜索时，建议增加按发布年份查询，主页列表的更新时间有点多余；
增加个功能，希望下次打开时窗口能恢复到上次的大小位置；
如果可以，增加本地播放的功能，就是可以播放电脑上的视频

**Comment by hooray** [comment]
说实话，看过源码后，我可以告诉你做不到。
筛选的条件是数据抓取网站提供的，抓去网站没提供按年份搜索，zyplayer就没办法支持，除非把数据抓取到本地，然后进行本地搜索。

**Comment by Hunlongyu** [comment]
本地播放功能建议使用一些功能强大的本地播放器.
软件功能多虽好, 但是也要考虑时间精力的.
