### ISSUE TITLE
卸载旧版下载新版后就不能用了（现在版本1.0.23）

### ISSUE THREAD

**Issue by God-xzz** [Hunlongyu/ZY-Player#127]
![效果图片](<img src="https://img04.sogoucdn.com/app/a/100520146/65c5c525486ccbbb0a9c175979dc9631" alt="Snipaste_2020-07-11_23-52-35.png" title="Snipaste_2020-07-11_23-52-35.png" />)

**Comment by God-xzz** [comment]
进入页面后都是中间一直在转圈，点开设置是空白页，没有切换影视源的窗体。

**Comment by God-xzz** [comment]
![效果图](https://img04.sogoucdn.com/app/a/100520146/65c5c525486ccbbb0a9c175979dc9631)

**Comment by Hunlongyu** [comment]
尝试下载内测版本： 1.1.4

**Comment by mpc2008cn** [comment]
昨天也遇到这问题了，设置里清除下缓存就好了

**Comment by God-xzz** [comment]
> 昨天也遇到这问题了，设置里清除下缓存就好了

不行，我设置里面一片空白，下载了1.1.4后好了
