### ISSUE TITLE
看电视剧没有自动播放下一集，能不能添加一个放完自动放下一集的功能？感谢

### ISSUE THREAD

**Issue by 762438624** [Hunlongyu/ZY-Player#129]
看电视剧没有自动播放下一集，能不能添加一个放完自动放下一集的功能？感谢

**Comment by Hunlongyu** [comment]
这个功能一直都有的呀。
是比较新的版本么？
最新内测版我还没有测试过， 明天测试一下。

**Comment by Hunlongyu** [comment]
刚刚测试一下可以自动播放下一集。 不过需要播放到最后一秒。

**Comment by Hunlongyu** [comment]
测试 正常,可以自动播放下一集, 请确认安装的是,最新内测版
