### ISSUE TITLE
视频源

### ISSUE THREAD

**Issue by shcqiu** [Hunlongyu/ZY-Player#130]
可否添加奈菲影视源?如何自定义编写视频源？谢谢！

**Comment by Hunlongyu** [comment]
视频源需要一定格式，不是随意输入网址就好了的。
最新内测可以导出， 和导入视频源。
你可以先导出复制到编辑器看看相关格式。

**Comment by Hunlongyu** [comment]
[源管理](http://zyplayer.fun/doc/sites/#%E7%AE%A1%E7%90%86%E6%BA%90)

相关文档已补充, 请自行查阅.
