### ISSUE TITLE
1.1.4内测版启动时报错“A javaScript error occured in the main process: Uncaught Exception: Error:listen EACCES: permission denied 0.0.0.0:4848

### ISSUE THREAD

**Issue by silencehust** [Hunlongyu/ZY-Player#132]
![Snipaste_2020-07-13_16-35-52](https://user-images.githubusercontent.com/11399539/87282570-ffd80e00-c526-11ea-921a-945b686cff71.png)

**Comment by Hunlongyu** [comment]
端口号被占用, 我尝试下个版本切换一个端口号吧

**Comment by Hunlongyu** [comment]
请下载新版本试一试.
