### ISSUE TITLE
linux下新版内测版本不能设置窗口保持最前面

### ISSUE THREAD

**Issue by flymouse** [Hunlongyu/ZY-Player#133]
linux是fedora32，zy-player用的是ImageApp格式的，老版本右键会出来一个菜单可以设置保持窗口在最前面，新版1.2.2内测版本右键没有菜单出现

**Comment by Hunlongyu** [comment]
没有 linux 测试环境, 不清楚. 
不过最新 v2.x 版本有置顶快捷键: t
