### ISSUE TITLE
能否自定义屏蔽某些种类视频，比如伦理片福利片等

### ISSUE THREAD

**Issue by shi-jie01** [Hunlongyu/ZY-Player#134]
有些类视频，如福利片伦理片的，我自己不需要，但我想把这个软件推荐给家人他们用，又怕他们不小心点到那里，会非常尴尬的，所以是否可自定义屏蔽某些种类视频

**Comment by supbose** [comment]
自己编译下兄弟！

**Comment by Hunlongyu** [comment]
最新正式版: v2.x 已发布, 欢迎体验.
