### ISSUE TITLE
mac的两个版本存在冲突

### ISSUE THREAD

**Issue by coolzhuo** [Hunlongyu/ZY-Player#136]
之前mac安装了1.0.23，看到有1.2.6内测版就覆盖了，然后打开界面的源显示空的只有-
又换回老版本显示就错乱了。直接是个多列的空白界面，源也看不到了，设置也点不开。

**Comment by Hunlongyu** [comment]
新内测版本, 第一次使用, 请重置软件一次, 重置功能在设置界面里.
