### ISSUE TITLE
关于体验上的几点优化建议

### ISSUE THREAD

**Issue by hooray** [Hunlongyu/ZY-Player#137]
这阵子我个人使用体验下来，感觉产品目前比较geek，不知道是不是作者定位就是如此，但我希望能更加接地气一点，这样我可以更好的推荐给身边的朋友，或者是给对操作上不是那么熟练的父母使用。

所以我有几个优化上的建议，看看是不是可以讨论下：

1. 下拉选择筛选目标源网站的操作，可以改成侧边tab选项卡的形式，这样一目了然，而且点击操作也从2次减少到了一次
2. 筛选结果列表页和收藏列表页以卡片的形式展示，放出海报图，因为有些资源可能会重名，尤其是电影类资源，更多时候可能需要靠海报来分辨
3. 收藏列表的同步功能改成点击进入详情页的时候，就自动获取一次最新的数据并展示，站在用户角度，既然会去点同步，目的其实就已经是想去观看了，所以点击同步，有更新再点击进入详情，有点多此一举。相反，列表页可以增加批量同步操作，批量操作可以让用户知道哪些资源有更新，当有多个资源更新了，用户会自行安排观看时间。
4. 关于播放窗口的逻辑，这块我使用起来总觉得有点别扭，但现在也说不上更好的办法，倒是我很喜欢youtube的逻辑。比如我从列表页找了个资源，点进入播放，这时候我其实是可以返回列表页，同时播放窗口会缩到右下角继续播放，这时我就可以选择是搜索其它资源进行播放，或者点击小窗口恢复原有状态观看。

**Comment by Hunlongyu** [comment]
感谢体验反馈.
1. 没有做成侧边 tab, 是因为这些资源网,里面的资源几乎都是重复的. 
2. 最新版的资源获取, 是通过这些网站的接口获取的. 搜索接口没有返回图片, 软件也就没有办法显示图片.
3. -
4. -

其实主要的是, 精力有限, 这个软件不再维护了.
