### ISSUE TITLE
✨新版本开发计划🎉

### ISSUE THREAD

**Issue by Hunlongyu** [Hunlongyu/ZY-Player#14]
新版本[开发计划](https://github.com/Hunlongyu/ZY-Player/projects)

软件官网下载量过10万之际, 开启新版本开发.

大家有什么需求和建议欢迎提出, 我会酌情加入下个版本开发计划. 共同完善软件.

**Comment by wy7414** [comment]
能做一个APK么

**Comment by kongxianglai-jack** [comment]
希望大佬能加入下载功能

**Comment by Hunlongyu** [comment]
@wy7414 
在考虑, 不过优先级无限靠后.

**Comment by Hunlongyu** [comment]
@kongxianglai-jack 
下个版本会放出, 不过下载功能会很弱, 毕竟收藏和手机播放功能. 
没有太多精力制作一个下载器.

**Comment by kongxianglai-jack** [comment]
请问一下，在这看电影会不会有缓存，如果有的话，建议加一个清理缓存的功能。

**Comment by iori8421** [comment]
有支持hash播放的计划吗

**Comment by Hunlongyu** [comment]
@iori8421 额~hash说实话,体验太差了,稍微冷门一点的资源都加载不了,或者播放卡顿. 所以不会有支持计划的.

**Comment by xu93nuo1987** [comment]
建议开发手机APP版，有投屏功能！

**Comment by xu93nuo1987** [comment]
建议开发手机APP版，有投屏功能！

**Comment by xu93nuo1987** [comment]
现在很多时间都不会用电脑看视频，多数都是手机APP找电视，电影然后投屏到电视观看！

建议开发手机APP版，有投屏功能！播放记录功能！

**Comment by xu93nuo1987** [comment]
播放速度希望有，1.25和1.75！

**Comment by yongyan681** [comment]
希望可以自定义加入视频采集网址

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
1. 手机版有考虑, 不过优先级靠后
2. 倍速我会在新版加入的

**Comment by Hunlongyu** [comment]
@yongyan681 
1. 没有那么简单的, 不是写个网址, 就能获取到资源, 需要写解析代码的. 而这部分的工作量相当大.
2. 如果有网址, 可以在这里推荐, 我会在下个版本考虑加入.

**Comment by yongyan681** [comment]
网上资源站有很多，搜索就能出来。我是小白，不知道你的播放列表信息是解析的还是采集的，可以看看Xyplayer的后台管理，或许是一个新思路。我的设想是播放列表采用采集的方式，播放器可以嵌入类似Xplayer的解析播放器，解析地址也采用可添加方式，解析地址调用添加的解析地址。

**Comment by yongyan681** [comment]
解析线路1=>https://z1.m1907.cn/?a=1&jx=
解析线路2=>http://zhiyun.ppdsw.xyz/yjx/index.php?url=
金桥解析=>https://5.5252e.com/jx.php?url=
农夫解析=>http://jx.nongfu123.top/?url=
大白视频解析=>http://api.myzch.cn/?url=
爱秀解析=>http://jx.52ishow.com/jx/?url=
白狐解析=>https://api.baihuzhicheng.wang/?url=
我爱解析=>http://vip.52jiexi.top/?url=
8B视频服务解析=>https://api.8bjx.cn/?url=
1992解析=>http://vip11.1992tv.top/jiexi/?url=
F云解析=>https://api.1ff1.cn/?url=
辉煌解析=>http://jx.hhwlkj.top/jx.php?url=
8090g全网视频解析1=>http://jiexi.zkoujie.cn/?url=
8090g全网视频解析2=>http://www.8090g.cn/ceshi/?url=
Playm3u8解析=>https://www.playm3u8.cn/jiexi.php?url=
盘古解析=>https://www.pangujiexi.cc/jiexi.php?url=
ckmov解析=>https://www.ckmov.vip/api.php?url=

**Comment by Hunlongyu** [comment]
@yongyan681 
额额~这个视频解析我知道, 实现的方式原理都不一样.
不过确实可以丰富软件功能. 嗯~ 那就在下个版本加入视频解析, 希望能实现吧.

**Comment by xu93nuo1987** [comment]
建议把“福利”设置不要太明显，最好根据自己设置才显示最好！

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
新版本由于显示分类的逻辑变了, 默认不会显示福利.

**Comment by xu93nuo1987** [comment]
浑龙yu  老大，这软件后期不会收费吧！

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
不会收费的哦~只会像现在这样贴上赞赏码, 扫码捐助.

**Comment by warden22** [comment]
混江龙大佬，刚进来看看现在进度怎么样，发现进步如此之大，反手给你一个赞！

**Comment by Hunlongyu** [comment]
@warden22 
😂 hun 读作 韩
最近工作上一直很忙, 周末也加班. 所以进度很慢,接下来还要连续工作11天,直到五一放假.
感觉分分钟 ICU 的节奏. 我尽量五一前发布第一个测试版.

**Comment by xu93nuo1987** [comment]
期待新版本，其实更期待APP！

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
新版本其实改动不大, 主要是增加一些新的功能.

APP 其实不要报太大的希望, 因为我还要学习新的手机软件编程语言, 功能估计也不会很全.

**Comment by xu93nuo1987** [comment]
只是个人习惯吧，电脑版用的少，手机版用的多，但也是投屏为主！
不过相信大神的实力！加油！

**Comment by heyzayz** [comment]
可以加个弹幕的功能不，
自动去除片头片尾，
选集在播放界面加个按钮也可以更方便
加油！

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
加油~ 💪

**Comment by Hunlongyu** [comment]
@heyzayz 
1. 弹幕功能目前实现不了
2. 自动去除片头片尾也实现不了
3. 选集由于插件不支持, 我也不打算花精力去实现.
主要是这是个无后台的播放器, 没有服务器去记录数据, 爬取的网站如果不支持, 我这边也很难实现.

**Comment by heyzayz** [comment]
> @heyzayz
> 
> 1. 弹幕功能目前实现不了
> 2. 自动去除片头片尾也实现不了
> 3. 选集由于插件不支持, 我也不打算花精力去实现.
>    主要是这是个无后台的播放器, 没有服务器去记录数据, 爬取的网站如果不支持, 我这边也很难实现.

活抓一个作者 哈哈，
选集的话 在播放界面的右边增加一个可以关闭的侧边栏呢

**Comment by Hunlongyu** [comment]
@heyzayz 
1. 新版本已经有播放列表和历史记录的侧边栏.
2. 不过这个侧边栏在软件界面内, 不在播放器界面内. 所以全屏后,是看不见侧边栏的.

**Comment by warden22** [comment]
混江龙你好，我看你新版加入了播放历史，上次播放位置记忆有吗？希望加入这个哈，不想重头开始看。
















在 2020-04-22 16:46:16，"Hunlongyu" <notifications@github.com> 写道：

@heyzayz

新版本已经有播放列表和历史记录的侧边栏.
不过这个侧边栏在软件界面内, 不在播放器界面内. 所以全屏后,是看不见侧边栏的.

**Comment by Hunlongyu** [comment]
@warden22 
1. 有播放历史, 也会记录上次播放位置.😎
2. 新版本功能基本已完成, 过两天会放出测试版, 希望 BUG 不要太多🤪

**Comment by heyzayz** [comment]
能够记录上次播放位置，就可以跳过片头片尾啊，，
片头：设置一个默认跳到的位置（比如1:30），
片尾：假如一共10分钟播放完毕，在播放到9分钟的时候自动下一集

**Comment by Hunlongyu** [comment]
@heyzayz 
大兄弟,
1. 你这是知道从 1:30 秒开始播放, 但是播放器不知道呀. 又不能每个视频都从 1:30 秒开始播放吧.
2. 同理, 片尾也是如此.
3. 记录播放位置, 是用了定时器. 目前软件每十秒记录一次当前播放进度.
4. 该软件你可以想象成本地播放器, 你的本地播放器并没有弹幕功能吧?也没有自动跳过片头片尾吧?
5. 你所说的这些功能,都是 优爱腾 这种大型播放平台, 后台记录各种数据, 通过大数据分析出来的.

**Comment by warden22** [comment]
赞，会帮忙测试的。大哥私信教下小老弟怎么做这个，可以帮忙分担点，奥里给！
















在 2020-04-24 14:22:54，"Hunlongyu" <notifications@github.com> 写道：

@warden22

有播放历史, 也会记录上次播放位置.
新版本功能基本已完成, 过两天会放出测试版, 希望 BUG 不要太多

**Comment by heyzayz** [comment]
> @heyzayz
> 大兄弟,
> 
> 1. 你这是知道从 1:30 秒开始播放, 但是播放器不知道呀. 又不能每个视频都从 1:30 秒开始播放吧.
> 2. 同理, 片尾也是如此.
> 3. 记录播放位置, 是用了定时器. 目前软件每十秒记录一次当前播放进度.
> 4. 该软件你可以想象成本地播放器, 你的本地播放器并没有弹幕功能吧?也没有自动跳过片头片尾吧?
> 5. 你所说的这些功能,都是 优爱腾 这种大型播放平台, 后台记录各种数据, 通过大数据分析出来的.

每个视频开头结束时间这个确实麻烦，
![image](https://user-images.githubusercontent.com/11624033/80194948-c097d080-864d-11ea-8625-1de16e4f537b.png)
如果这样加个开关呢  不知道行不行 可能会麻烦很多，
比起这些功能 还是更期待新版本早点出  哈哈

**Comment by xu93nuo1987** [comment]
最新资源网的视频分享或者手机连接不能打开，能否给个最新资源网的地址啊！

**Comment by Build924211** [comment]
15版本 自动播放下一集会跳到下下一集

**Comment by xu93nuo1987** [comment]
能否加个搜索全网的搜索！

**Comment by xu93nuo1987** [comment]
建议添加个能全资源搜索的页面或者按钮！
每个资源门开搜索的确有点难找！

**Comment by vicedev** [comment]
> 能做一个APK么

[ZY-Player-Android](https://github.com/vicedev/ZY-Player-Android)，可以看下我做的这个Android版本~

**Comment by vicedev** [comment]
> 建议开发手机APP版，有投屏功能！

[ZY-Player-Android](https://github.com/vicedev/ZY-Player-Android)，可以看下我做的这个Android版本~
