### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by bug0306** [Hunlongyu/ZY-Player#140]
![image](https://user-images.githubusercontent.com/48059017/88272209-f3179f00-cd0a-11ea-9d13-ee7c1acc3e3c.png)
一旦筛选为电视剧或者电影之类的就显示No result

**Comment by JesseXia** [comment]
我也是这个情况

**Comment by Hunlongyu** [comment]
这个是别人服务器接口问题,不是软件问题. 该分类就是没有资源.
