### ISSUE TITLE
2.0.0 版本 条目显示有数量限制 显示不完全

### ISSUE THREAD

**Issue by syfirefox** [Hunlongyu/ZY-Player#144]
2.0.0 版本 列表模式 资源搜索关键字后 条目显示有数量限制 显示不完全，不能下拉显示更多。

**Comment by Hunlongyu** [comment]
不会的, 逻辑里没有限制, 可能是服务器返回的数据不全吧

**Comment by syfirefox** [comment]
逻辑可能没有问题 可能是显示或者是分页的问题  因为1.9X版和2.0版在同一个资源网站 搜寻同一个关键字 返回的结果明显数量显示差别巨大  参考测试关键字“国语”  侧拉条并不能拉取更多结果
