### ISSUE TITLE
无法播放视频

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [Hunlongyu/ZY-Player#145]
升级2.0版本后，无法搜索视频，无法播放视频。望解决，ᠪᠠᠨᡳᡥᠠ/巴尼哈（谢谢）。

**Comment by Hunlongyu** [comment]
首次使用 2.0 版本， 需要重置一下软件。 重置功能在设置里。

爱新觉罗启钰 <notifications@github.com> 于2020年7月25日周六 下午7:29写道：
