### ISSUE TITLE
Mac 2.0 连不了网络

### ISSUE THREAD

**Issue by 743ren** [Hunlongyu/ZY-Player#146]
系统自带防火墙弹出提示是否允许网络接入，点击允许后，左上角的资源网站选择列表什么都没有，搜索也没反应

**Comment by louiejordan** [comment]
Windows也连不了

**Comment by Hunlongyu** [comment]
所有源都不行么？一般是服务器不稳定导致的

Louie <notifications@github.com> 于2020年7月26日周日 下午10:09写道：

**Comment by JIACHENG135** [comment]
> 系统自带防火墙弹出提示是否允许网络接入，点击允许后，左上角的资源网站选择列表什么都没有，搜索也没反应

您好,Mac用户可以试用下我开发的App JCPlayer. 
[主页](https://jcplayer.me)
[Github](https://github.com/JIACHENG135/JCPlayer)
