### ISSUE TITLE
蓝奏云网盘链接失效

### ISSUE THREAD

**Issue by westCastle** [Hunlongyu/ZY-Player#148]
蓝奏云网盘链接失效
![image](https://user-images.githubusercontent.com/33519116/88505790-ffea0a80-d00a-11ea-9f35-30cc80b2ece7.png)

**Comment by Hunlongyu** [comment]
我这边刚刚尝试了一下， 链接没有失效哦~

如果不行的话， 尝试从 GitHub 官网下载吧。

westCastle <notifications@github.com> 于2020年7月27日周一 下午1:14写道：
