### ISSUE TITLE
添加用户注册登录功能

### ISSUE THREAD

**Issue by warden22** [Hunlongyu/ZY-Player#15]
昨晚和今天都无法搜索资源了，服务器有问题了吗？
另外建议大佬添加用户注册登录功能，用户可添加变更搜索源，有离线到其他盘和本地下载功能。好的应用在后期值得推广，希望能永久免费，不要学某某视频需要充会员，得民心者得天下，自会有用户多多打赏。不忘初心，放得始终！

**Comment by Hunlongyu** [comment]
1. 搜索源目前是可以切换的呀, 搜索框前, 有个资源网站的名字, 点击后, 出现下拉框. 里面有其他资源网站.
2. 登录注册功能,目前没有什么用处吧,软件没有限制, 不需要登陆注册也能使用全部功能. 不过如果需要访问密码, 加密收藏夹, 倒是可以考虑.
3. 由于视频资源的原因, 技术上无法实现离线, 即使获取到资源链接, 百度网盘什么的也离线不了.
4. 本地下载确实有考虑过, 但是技术上挺难实现的, 不过我会记录下来, 未来有能力的话, 我会加上的.
5. 感谢支持推广, 软件保证永久免费的. 也感谢大家的打赏.

**Comment by wuwujia** [comment]
> 1. 搜索源目前是可以切换的呀, 搜索框前, 有个资源网站的名字, 点击后, 出现下拉框. 里面有其他资源网站.所有资源都是资源网站的,如果他的服务器出问题了, 确实会影响到该软件使用.不过可以尝试切换视频源.
> 2. 登录注册功能,目前没有什么用处吧,软件没有限制, 不需要登陆注册也能使用全部功能. 不过如果需要访问密码, 加密收藏夹, 倒是可以考虑.
> 3. 由于视频资源的原因, 技术上无法实现离线, 即使获取到资源链接, 百度网盘什么的也离线不了.
> 4. 本地下载确实有考虑过, 但是技术上挺难实现的, 不过我会记录下来, 未来有能力的话, 我会加上的.
> 5. 感谢支持推广, 软件保证永久免费的. 也感谢大家的打赏.

想要播放流畅的体验，播放源是最重要的，建议多更新流畅的源，比如小小影视，冬瓜影视的源

**Comment by Hunlongyu** [comment]
1. 下一个版本正在开发, 新版本会有很多视频源
2. 你说的两个网站,我看了一眼,和我用的源都差不多. 其实视频源就那么几个. 网上的很多视频网站都是用的相同的源.

**Comment by Github2019Cn** [comment]
为了检测福利搜索到的春宫妖姬 播放没声音？资源有问题吗？还是安装版本的有？还有个人觉得那个福利选项可以删除不必要啊。91美剧  菲菲影视 奈菲影视  1090影视  完美看看  速影tv  NO影视  资源虽然片源相同但可以考虑添加  http://vipbox.ml/  会员盒子 搜索功能可以考虑下    最后重要的是下载功能。功能完善可以考虑移动端了。最后祝大佬身体健康,工作顺利！

**Comment by Hunlongyu** [comment]
@Github2019Cn 
1. 如果播放其他视频有声音而某个视频没声音,基本可以判断是这个资源有问题.
2. 话说没有福利选项啊? 是官网下载的么?因为软件开源, 有可能是第三方魔改的.
3. 如果是福利分类的话, 那是因为资源网站也是这么分类的.
4. 更多的视频源正在适配, 不过你列出的网站, 有的视频源和我用的相同; 有的是做了防盗链处理, 用不了.
5. http://vipbox.ml/ 这个网站有明确指出,任何单位或个人未经许可不可使用.
6. 搜索功能不是有的么?
7. 下载功能会在下个版本放出来, 不过可能你们想象的不太一样. 毕竟软件主要是播放功能.
8. 移动端还在考虑, 主要是想用一个新的语言写, 要花大量时间去学习这门语言. 所以能不能做出来, 还不一定.

**Comment by Zara1999** [comment]
大佬，今天发现无法搜索资源了，首页的资源也加载不出来了。

**Comment by Hunlongyu** [comment]
@Zara1999 切换视频源试一试
