### ISSUE TITLE
Win新版本无法选择资源且无法搜索

### ISSUE THREAD

**Issue by onemoretime0** [Hunlongyu/ZY-Player#151]
Windows10 v2.0.0版本, 无法选择资源来源, 搜索不到资源

**Comment by 905407220** [comment]
同样的问题，求解啊 1.0版本还阔以的

**Comment by weiyongsheng2018** [comment]
win10最新系统安装后安全没法用，安装后一篇空白，资源列表为空，也不能搜索，急需解决

**Comment by 905407220** [comment]
> win10最新系统安装后安全没法用，安装后一篇空白，资源列表为空，也不能搜索，急需解决
在设置那里重置一下

**Comment by Hunlongyu** [comment]
安装最新版本, 在设置界面点击软件重置功能. 重启软件即可.
