### ISSUE TITLE
请问mac版本的是我的问题还是没有完全汉化过来

### ISSUE THREAD

**Issue by Roadmanteacher** [Hunlongyu/ZY-Player#155]
菜单多数是英文的 

file edit 个别是中文的

**Comment by Hunlongyu** [comment]
我没有mac 电脑, mac的安装包是系统打包的. 所以我并不清楚 mac 下具体什么情况.

**Comment by JIACHENG135** [comment]
mac版欢迎了解我的项目,不过资源比不了,但是界面还行,上周开始搞的, cmd + c + 1 或 2,3,4,5,7 切换主题, 有什么问题欢迎提issue
[JCPlayer](https://jcplayer.me)
