### ISSUE TITLE
No results :(

### ISSUE THREAD

**Issue by hustbind** [Hunlongyu/ZY-Player#156]
No results :( 
运行显示No results :(

**Comment by JIACHENG135** [comment]
> No results :(
> 运行显示No results :(

Hust校友好呀,欢迎试用我开发的App JCPlayer. PS: longyu兄对不住了,打扰了 🤦‍♂️
[主页](https://jcplayer.me)
[Github](https://github.com/JIACHENG135/JCPlayer)

**Comment by Coolkkmeat** [comment]
#158 看这个，我发的评论

**Comment by Hunlongyu** [comment]
尝试切换不同的视频源, 或者 分类.

**Comment by hustbind** [comment]
视频源是空的，点重置没有反应
