### ISSUE TITLE
无法使用了，进去什么都没有

### ISSUE THREAD

**Issue by Corey-1** [Hunlongyu/ZY-Player#158]
![Snipaste_2020-07-31_20-50-22](https://user-images.githubusercontent.com/53885447/89036568-7a9a8900-d36f-11ea-8c27-b04c54fa09b6.png)

**Comment by kuu-an** [comment]
同上，更新后直接没得用了

**Comment by JIACHENG135** [comment]
> 同上，更新后直接没得用了
欢迎试用这个项目 [JCPlayer](https://jcplayer.me)

**Comment by lllxylh** [comment]
我的和你的一样，什么都看不到了，作者还更新吗？不更新给大家说下啊

**Comment by Coolkkmeat** [comment]
复制自2.0.0的说明文档中：
`v2.x 版本与 v1.x 版本不兼容, 建议卸载 v1.x 版本, 并在 v2.x 版本中, 重置软件`
重要的是重置软件，我试了一下就可以了。

**Comment by kuu-an** [comment]
> 复制自2.0.0的说明文档中：
> `v2.x 版本与 v1.x 版本不兼容, 建议卸载 v1.x 版本, 并在 v2.x 版本中, 重置软件`
> 重要的是重置软件，我试了一下就可以了。

已经可以了，感谢提醒

**Comment by hustbind** [comment]
点重置没有反应啊~~

**Comment by Coolkkmeat** [comment]
> 点重置没有反应啊~~

诶？核对一下流程：卸载旧软件，安装新软件，打开之后到设置里重置。然后软件会自动关闭，手动打开就可以了。
如果还是不行，那我也不清楚了。
