### ISSUE TITLE
今天下载的最新的版本，安装点击按钮一直转圈圈，网络一切正常就是看不到内容

### ISSUE THREAD

**Issue by weiyongsheng2018** [Hunlongyu/ZY-Player#16]

**Comment by weiyongsheng2018** [comment]
<img width="792" alt="zy_player" src="https://user-images.githubusercontent.com/40163275/77049697-82cadb00-6a03-11ea-9fc1-1813384b28ab.png">

**Comment by Hunlongyu** [comment]
切换左下角的视频源。由于访问人数过多，卡顿了。切换视频源应该可以解决这个问题。
