### ISSUE TITLE
下载功能无法使用

### ISSUE THREAD

**Issue by guohungwei** [Hunlongyu/ZY-Player#164]
点击下载没反应，没有任何提示。

**Comment by kentcc88** [comment]
我试了，也用不了下载功能，暂时还没开通吗？

**Comment by LyonelCai** [comment]
2.3.5 版本 下载功能有点问题。以前可以用 XDM 下载，现在不行了。

**Comment by guohungwei** [comment]
唉，期待后续更新吧。

**Comment by cuiocean** [comment]
2.4.3版本中下载没反应的问题已经解决.

**Comment by LyonelCai** [comment]
下载是可以了，但是还是有些不方便，就是有两个以上可以下载的连接的话，就需要先在notepad copy+paste
然后再从里面选自己想下载的链接。有待更新。
