### ISSUE TITLE
视图—列表模式

### ISSUE THREAD

**Issue by taurusduan** [Hunlongyu/ZY-Player#169]
建议视图里面加入之前就有的分页，自己用下来感觉瀑布流很鸡肋，无法进行快速定位，并且如果在使用海报的时候，瀑布流加载缓慢，经常无法加载。所以，请求在列表模式中加入之前就有的分页功能。非常感谢！

**Comment by JIACHENG135** [comment]
> 建议视图里面加入之前就有的分页，自己用下来感觉瀑布流很鸡肋，无法进行快速定位，并且如果在使用海报的时候，瀑布流加载缓慢，经常无法加载。所以，请求在列表模式中加入之前就有的分页功能。非常感谢！

你好呀，欢迎试用一下我开发的一款类似软件，JCPlayer，目前我就是使用分页设计的检索结果页，欢迎提issue！
[JCPlayer - Github](https://github.com/JIACHENG135/JCPlayer)
