### ISSUE TITLE
调用外置播放器Potplayer

### ISSUE THREAD

**Issue by ValarBinis** [Hunlongyu/ZY-Player#173]
尊敬的作者大大：
       AMD显卡有个**插帧**功能，但是需要配合着Potplayer才可以使用。不知道ZY player可不可以调用外部的播放器Potplayer用作视频播放好满足插帧的要求。
       以前用迅雷边下边播的时候是修改了配置文件里的播放器地址，不知道这个可不可以呢

**Comment by myjlpt** [comment]
直接去采集站点，复制链接放到POT中播放就好

**Comment by myjlpt** [comment]
采集站点列表
八戒资源          http://bajiezy.cc

麻花资源          http://www.mahuazy.net

最大资源          http://zuidazy.net

156资源            http://www.1156zy.net

酷云资源          http://kuyunzy.cc

ok资源              http://www.haozy.cc 

605资源            http://www.765zy.com

1866资源          http://www.1886zy.net

123资源网        http://www.123ku.com

看看资源        http://kankanzy.com

高清资源          http://gaoqingzy.com

乐多资源         http://www.leduozy.com

永久资源         http://yongjiuzy.cc

步步高资源     http://www.bbkdj.com/help

c值云资源       http://www.czhiziyuan.com

酷播资源         http://kubozy.net

最新资源         http://www.zuixinzy.cc

搜乐资源网     https://www.solezy.com

魔卡资源网     https://mokazy.com

超快资源         http://265zy.cc

88资源网        http://www.88zyw.net

**Comment by ValarBinis** [comment]
> 采集站点列表
> 八戒资源 http://bajiezy.cc
> 
> 麻花资源 http://www.mahuazy.net
> 
> 最大资源 http://zuidazy.net
> 
> 156资源 http://www.1156zy.net
> 
> 酷云资源 http://kuyunzy.cc
> 
> ok资源 http://www.haozy.cc
> 
> 605资源 http://www.765zy.com
> 
> 1866资源 http://www.1886zy.net
> 
> 123资源网 http://www.123ku.com
> 
> 看看资源 http://kankanzy.com
> 
> 高清资源 http://gaoqingzy.com
> 
> 乐多资源 http://www.leduozy.com
> 
> 永久资源 http://yongjiuzy.cc
> 
> 步步高资源 http://www.bbkdj.com/help
> 
> c值云资源 http://www.czhiziyuan.com
> 
> 酷播资源 http://kubozy.net
> 
> 最新资源 http://www.zuixinzy.cc
> 
> 搜乐资源网 https://www.solezy.com
> 
> 魔卡资源网 https://mokazy.com
> 
> 超快资源 http://265zy.cc
> 
> 88资源网 http://www.88zyw.net

太谢谢了！有这些资源网站就可以用Python写一个自动生成播放列表DPL文件了!再次感谢

**Comment by myjlpt** [comment]
@ValarBinis 敢问这个你准备怎么筛选??m3u8才能正常播放的。其它地址不能正常播放。

最好能打包成EXE分享一下呗。pip install pyinstaller ;pyinstaller -F -w *.py
用这个应该可以打包成EXE

**Comment by cuiocean** [comment]
2.4.2版本支持从PotPlayer中打开视频了.

**Comment by ValarBinis** [comment]
> 2.4.2版本支持从PotPlayer中打开视频了.

哇，试了下，确实可以直接导入到Potplayer中。现在看着就很舒服了，纵享丝滑。。。嘻嘻嘻
不过Potplayer总是会遇到网站证书提醒，然后报错（当然这是Potplayer的问题，就算是复制的链接也是这样），不过第二次再播放的时候就可以了。
谢谢作者，这软件很好用

**Comment by ValarBinis** [comment]
> @ValarBinis 敢问这个你准备怎么筛选??m3u8才能正常播放的。其它地址不能正常播放。
> 
> 最好能打包成EXE分享一下呗。pip install pyinstaller ;pyinstaller -F -w *.py
> 用这个应该可以打包成EXE

昨天才开始做，虽然ZYplayer的作者更新了可以对用外置播放器，但是在电视剧方面只能推一集过去，所以我昨天开始做了这个，现在做完了。https://github.com/ValarBinis/OK-for-dpl。只做了ok资源网的，可以按照那个py文件修改url和Xpath即可

**Comment by cuiocean** [comment]
@ValarBinis 我已把该功能做进了ZY Player里面。现在可以直接在PotPlayer里打开所有剧集，并从当前集开始播放。会在2.4.4中发布。

**Comment by myjlpt** [comment]
@ValarBinis @cuiocean OK！好用，这样爬出来的结果，可以直接导入TV的DIYPLAYER的壳子里，不要一个一个录入了。
