### ISSUE TITLE
最新版2.4.0无法使用

### ISSUE THREAD

**Issue by jay763190097** [Hunlongyu/ZY-Player#186]
![截图录屏_zy_20200822232121](https://user-images.githubusercontent.com/16317178/90959613-9c9aad80-e4ce-11ea-84d5-d327e280a8da.png)
![image](https://user-images.githubusercontent.com/16317178/90959624-a91f0600-e4ce-11ea-990a-01e198633dd8.png)
![image](https://user-images.githubusercontent.com/16317178/90959632-bb00a900-e4ce-11ea-9111-09fdfe1c160e.png)

**Comment by jay763190097** [comment]
@cuiocean 用的Linux deepin V20系统，该删什么文件呢

**Comment by buvta** [comment]
~/.config/zy 配置文件全在这儿，删除(丢失配置)或改名

**Comment by tokenian** [comment]
@cuiocean mac删什么文件呢

**Comment by cuiocean** [comment]
旧的版本工作吗？如果用别的播放器或在线播放器打开m3u8链接 工作吗？

**Comment by jxjxjhjh** [comment]
> 旧的版本工作吗？如果用别的播放器或在线播放器打开m3u8链接 工作吗？

测试过 2.2 2.3 2.4都不行，重装系统后出现的，之前可以，但是，是同一个系统  manjaro

**Comment by buvta** [comment]
archlinux没问题，感觉最可能是权限问题 [ How to run an AppImage](https://discourse.appimage.org/t/how-to-run-an-appimage/80)，如果还是照旧试着用源码编译运行

**Comment by jay763190097** [comment]
@buvta 删除以前的文件之后可以用了
