### ISSUE TITLE
可以增加跳过片头片尾的功能么？

### ISSUE THREAD

**Issue by bdkiller** [Hunlongyu/ZY-Player#188]
可以增加跳过片头片尾的功能么？最好能自定义片头片尾长度或时间点。

**Comment by supbose** [comment]
想多了兄弟。

**Comment by cuiocean** [comment]
@bdkiller 2.4.4版本支持在PotPlayer中打开所有剧集，你可以在PotPlayer里面设置跳过片头片尾
![image](https://user-images.githubusercontent.com/5760235/91617695-d8c78580-e988-11ea-8b3a-2ef9098a5410.png)
