### ISSUE TITLE
2.4.1版本

### ISSUE THREAD

**Issue by Masterpiece-K** [Hunlongyu/ZY-Player#189]
目前版本收藏功能还是不可用，如下图所示
![QQ图片20200825175413](https://user-images.githubusercontent.com/52354465/91160770-680c3900-e6fc-11ea-9c8b-ab213c87bc66.png)
![QQ图片20200825175408](https://user-images.githubusercontent.com/52354465/91160794-6f334700-e6fc-11ea-843e-faaa543932d0.png)

**Comment by cuiocean** [comment]
估计你要重置一下

**Comment by Masterpiece-K** [comment]
> 估计你要重置一下

我重置过几次了发现还是这样，如果别人那里没出现这个情况的话可能就是我这边有问题了

**Comment by cuiocean** [comment]
我有几次出现问题，清理一下prefetch里的文件后就好了，你可以装个everything，搜一下zy player，把不需要的文件清理一下。

**Comment by Masterpiece-K** [comment]
> 我有几次出现问题，清理一下prefetch里的文件后就好了，你可以装个everything，搜一下zy player，把不需要的文件清理一下。

好的，谢谢，已经解决了

**Comment by Masterpiece-K** [comment]
> 我有几次出现问题，清理一下prefetch里的文件后就好了，你可以装个everything，搜一下zy player，把不需要的文件清理一下。

好的，谢谢已经解决了

**Comment by ouhuang-123** [comment]
我也有相同的情况，请问你是如何解决的
