### ISSUE TITLE
心得建议

### ISSUE THREAD

**Issue by arthur1976** [Hunlongyu/ZY-Player#190]
这个播放器我是2个月前才发现感觉不错哦，从此沉迷于追逐更新。。。这几次更新我觉得全局搜索和提供第三方播放最棒。
经常出现的问题就是打开剧集电影时加载有点慢有时还打不开。界面能在做的漂亮点就更好了

**Comment by cuiocean** [comment]
多谢反馈. 如果时加载慢的话,那基本就是源的问题. 把那些源都试试,选择对你比较快的源. 我常用麻花,秒播.

**Comment by JIACHENG135** [comment]
要不要试下这个播放器JCplayer，资源不多但是后续会接更多资源站！
[JCPlayer](https://jcplayer.me)
[Github](https://github.com.JIACHENG135/JCPlayer)
