### ISSUE TITLE
2.4.2使用POTPLAYER无法播放视频

### ISSUE THREAD

**Issue by q89539318** [Hunlongyu/ZY-Player#191]

**Comment by cuiocean** [comment]
请先确认该视频能否在ZY Player里播放

**Comment by q89539318** [comment]
确认在ZY 里面正常播放，附件是录制的问题视频，可以看看什么问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hunlongyu/ZY-Player"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 晚上9:36
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"金园木业"<576644034@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] 2.4.2使用POTPLAYER无法播放视频 (#191)





 
请先确认该视频能否在ZY Player里播放
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

录制_2020_08_28_10_12_41_324.mp4 (1.39M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=666236616bf2d1cbf181684314340a1b0252010300070d001e0654500a190c000a5b1b5906040d190b0705540b0c0c0d57010253321438f68fb4f03e00040a046c520e3e000c6705033d07536d00096b0050024f5f440c340e&t=exs_ftn_download&code=3b6a2484

**Comment by cuiocean** [comment]
这是PotPlayer本身的问题,有人遇到过同样的问题.据说第二次打开就没有问题了. 你可以试试,点击复制调试信息,或者时下载,然后把m3u8地址直接复制到PotPlayer里面,你应该也会遇到同意的问题.
