### ISSUE TITLE
可以增加个停止按钮吗

### ISSUE THREAD

**Issue by hualuoshuijia** [Hunlongyu/ZY-Player#192]
可以增加个停止按钮吗

**Comment by hualuoshuijia** [comment]
而且总是出现这样的状态

![image](https://user-images.githubusercontent.com/49584289/91278872-5c317d00-e7b7-11ea-9f93-ccf3f4dff044.png)

**Comment by hualuoshuijia** [comment]
最新页  应该是网站的首页吧   这样可以方便看电视剧电影的及时更新内容，


![image](https://user-images.githubusercontent.com/49584289/91279342-f0034900-e7b7-11ea-93f5-071dc33a3885.png)


![image](https://user-images.githubusercontent.com/49584289/91279380-fbef0b00-e7b7-11ea-9375-886e138ce313.png)

**Comment by hualuoshuijia** [comment]
没有首页或最新的标签，并且如果可以添加 一个   更新  按钮  能方便更新，

![image](https://user-images.githubusercontent.com/49584289/91280137-f219d780-e7b8-11ea-8dad-f44cbd76e88c.png)

![image](https://user-images.githubusercontent.com/49584289/91280187-0362e400-e7b9-11ea-964d-a154667a837c.png)

**Comment by cuiocean** [comment]
如果显示No Results就是api没有返回内容。我发现，电影，电视剧，和动漫，三个分类是不会返回结果的。你需要选择子分类。这应该是那些资源网站的api的问题。

**Comment by cuiocean** [comment]
更新页面问题已在2.4.3版本中解决
