### ISSUE TITLE
首页建议参考下h-player-v2

### ISSUE THREAD

**Issue by buvta** [Hunlongyu/ZY-Player#194]
[h-player](https://github.com/ZyqGitHub1/h-player-v2)的源里有个url与api地址可能不同，首页显示的是这个url的内容；zy-player首页显示的是api返回的内容，有些条目比较久远
添加个显示标志表示正在刷新加载，现在切换到一个源如果慢的话就是一片空白
设置里面添加“控制台”——在需要时可以打开开发者工具
添加“[清空缓存](https://github.com/atom/electron/blob/master/docs/api/session.md#sesclearcache)”(或者在退出时自动清空缓存)及[代理](https://stackoverflow.com/questions/37393248/how-connect-to-proxy-in-electron-webview)
h-player源的设置也可以适当参考下，其播放界面感觉有点别扭

**Comment by cuiocean** [comment]
我看了h-player，也是api返回的内容，就是顺序有些不同而已。我已改进了一下，现在最新及子分类，都是按照更新时间顺序排列。

**Comment by supbose** [comment]
没有参考价值

**Comment by buvta** [comment]
> 没有参考价值

我说的是参考源如何设置，而不是源地址

**Comment by supbose** [comment]
哦。。嗯那样是可以的哈！的确！！

**Comment by buvta** [comment]
zy-player里显示的是上映年份，但却是最近才更新
现在的刷新标志希望可以改得更显眼点，还有默认源表第一次切换到“速播资源站”时一片空白但直接再次切换又能获取到内容，切换到其他源有时也会出现这种情况
控制台可用快捷键Ctrl+Shift+I调出
直接清空Cache文件夹不影响进度保存
代理可参考chrome配置步骤，使用系统代理配置

**Comment by supbose** [comment]
最近几次的频繁更新，问题多多了

**Comment by buvta** [comment]
第二条老版本也存在，最近更新添加的新功能还是比较方便的

**Comment by buvta** [comment]
确认app问题，数据返回正常，但显示不正常

![2020-08-27-194939_1080x720_scrot](https://user-images.githubusercontent.com/12312540/91438804-8d38ad00-e89e-11ea-8601-0e365e1686e4.png)

**Comment by cuiocean** [comment]
多谢各位的反馈。最近几次更新，收藏的数据都有变化，又因为可以在几个不同地方点击收藏，而彼此的代码又是独立的，所以导致一些bug。我在2.4.3版本中试图统一一下收藏的数据。

**Comment by cuiocean** [comment]
请更新2.4.6 支持编辑源，添加新源，拖曳源排序
