### ISSUE TITLE
鼠标指向进度条时显示缩略图   这个功能能增加吗

### ISSUE THREAD

**Issue by hualuoshuijia** [Hunlongyu/ZY-Player#198]
鼠标指向进度条时显示缩略图

**Comment by hualuoshuijia** [comment]
而且    打开详情页之后  侧边栏就没有选项卡了     

![image](https://user-images.githubusercontent.com/49584289/91544134-e1e93000-e951-11ea-93b0-578426970791.png)

**Comment by cuiocean** [comment]
鼠标指向进度条时显示缩略图应该是不能实现,视频不是本地的. 第二个问题已解决,会出现在2.3.4版本中
