### ISSUE TITLE
希望出 Mac 版 release

### ISSUE THREAD

**Issue by zronghui** [Hunlongyu/ZY-Player#2]

**Comment by Hunlongyu** [comment]
没有mac电脑，无法生成mac软件包。
也不想装黑苹果。
当然欢迎 @有mac 电脑的开发者帮忙生成 mac 版。

**Comment by Hunlongyu** [comment]
目前筹划新的版本, 计划在下一个版本推出支持 mac ,linux, windows三平台. 敬请关注

**Comment by Hunlongyu** [comment]
@zronghui 
Mac 版本已推出, 目前还处于内测中, 欢迎尝鲜哦~🤞

**Comment by zronghui** [comment]
> @zronghui
> Mac 版本已推出, 目前还处于内测中, 欢迎尝鲜哦~🤞

惊喜

**Comment by Hunlongyu** [comment]
@zronghui 
额额~ 因为还在内测, 可能有很多bug , 欢迎测试哈~
