### ISSUE TITLE
普通模式  和  精简模式  之间相互切换时 好像又要重新缓存，总是转圈圈，

### ISSUE THREAD

**Issue by hualuoshuijia** [Hunlongyu/ZY-Player#202]
普通模式  和  精简模式  之间相互切换时 好像又要重新缓存，音量好像也变了，

切换至精简模式后，播放器窗口大小比例不能适应视频高宽比例，需要调整播放器窗口，

**Comment by hualuoshuijia** [comment]
精简模式下   不显示进度条

**Comment by hualuoshuijia** [comment]
这俩下载挺快的,您看是不是对软件有帮助,对于一些速度慢点资源网站,总是等缓存没耐心,希望软件更加完善

[原创工具]M3U8= V1.4.5 [7]9]
https://www.52pojie.cn/thread-1216473-1-1.html

image
![image](https://user-images.githubusercontent.com/49584289/91919932-1ebe7980-ecfa-11ea-8390-e0b7d395fbc7.png)


m3u8loader+
https：//www.coolapk.com/apk/ru.yourok.m3u8loader（https：//github.com/YouROK/m3u8）

这俩下载挺快的,您看是不是对软件有帮助,对于一些速度慢点资源网站,总是等缓存没耐心,希望软件更加完善

**Comment by Hunlongyu** [comment]
目前已加上缓存功能.试一试呢
