### ISSUE TITLE
建议两个功能

### ISSUE THREAD

**Issue by xu93nuo1987** [Hunlongyu/ZY-Player#203]
1.添加跳过片头片尾功能，就是偏头多少分多少秒播放，片尾多少分多少秒结束播放下集，时间可以自己改，外加开关！

2.窗口大小可以修改，自动保存大小，下次打开默认上次使用大小！

**Comment by cuiocean** [comment]
@xu93nuo1987 第一个功能可以在第三方播放器中实现，比如potplayer。 目前没有计划把该功能做进去。 第二个是不错的需求。
