### ISSUE TITLE
关于第三方播放器打开的建议

### ISSUE THREAD

**Issue by Darling-Lee** [Hunlongyu/ZY-Player#204]
现在是第三方播放器打开的时候，没有理解错是将目前播放源编译成一个dpl的播放列表文件给potplayer，我建议改用m3u（或者m3u8）的文件，这个文件格式大部分的播放器都支持（包括potplayer等一系列支持网络播放的播放器）。这样也能解决Mac和Linux这个第三方播放器打开的功能形同虚设的问题（实测Linux下选择了SMPlayer提示不支持Dpl文件，Mac下根本选择不了播放器，即使能选，找支持DPL的播放器也有得烦。

**Comment by cuiocean** [comment]
dpl文件里面只是存放了几个m3u8的在线链接而已. 我试了一下SMPlayer,它根本就无法播放在线的m3u8. 你可以试试别的播放器

**Comment by cuiocean** [comment]
我试了一下VLC，它支持m3u8，不支持dpl。可以考虑加个选项，选择dpl或者是m3u8

**Comment by Darling-Lee** [comment]
SMPlayer支持m3u的啊，我一直都是这样在linux下观看电视节目的。另外，我知道Dpl是存放各个m3u链接的东西，也知道他跟m3u文件格式差别。我自己在windows下将源码中的play.vue里头的计算dpl文件里头的代码修改为计算m3u的动作。在windows下编译通过了。目前第三方打开无误。等下去linux下编译试试。


| |
Lee
|
|
lonelybboylonely@163.com
|
签名由网易邮箱大师定制
在2020年9月1日 02:38，cuiocean<notifications@github.com> 写道：

dpl文件里面只是存放了几个m3u8的在线链接而已. 我试了一下SMPlayer,它根本就无法播放在线的m3u8. 你可以试试别的播放器

**Comment by Darling-Lee** [comment]
m3u文件是基本所有支持网络播放的播放器都会支持的。某些播放器不支持读取里面的播放列表，只能上一集下一集的切换，像SMPlayer,VLC，mac下的IINA等这些是支持读取m3u文件里记录的播放列表，也支持在软件播放列表随意切换的。我知道你是否清楚就回复下这个，您可以参考一下。另外，Mac下您是否做过测试？我实测无法选择播放器，原因可能是只能指定可执行文件，而MacOSX下软件的方式只是一个带有.app后缀的文件夹，而在选择的时候并不能指定到.app的内部。


| |
Lee
|
|
lonelybboylonely@163.com
|
签名由网易邮箱大师定制
在2020年9月1日 02:42，cuiocean<notifications@github.com> 写道：

我试了一下VLC，它支持m3u8，不支持dpl。可以考虑加个选项，选择dpl或者是m3u8

**Comment by cuiocean** [comment]
已经改进，现在是导出m3u格式的文件。

**Comment by cuiocean** [comment]
我是在Windows下开发，所以Mac没有测试过。
