### ISSUE TITLE
将软件第三方播放器打开由dpl播放列表换成m3u播放列表打开的建议-续

### ISSUE THREAD

**Issue by Darling-Lee** [Hunlongyu/ZY-Player#205]
dpl文件应该是potplayer的专属播放列表（瞎说，无据），而m3u是大部分（几乎所有支持播放网络资源的播放器）都支持。目前测试修改了部分代码，并在Win,Lin平台变异编译成功后运行，均能实现完美（原Linux下没有支持dpl的播放器，换成m3u后，测试了只要支持网络资源播放的播放器（VLC,SMPlayer,MPlayer等)均能实现第三方播放器打开的功能。同时Win下也不再单纯支持Potplayer。
测试平台：Windows 10,Arch Linux 64
Linux桌面：DDE
测试播放器：SMPlayer,VLC,Potplayer......
测试结果：功能完美。

修改内容：
./src/components/Play.vue文件  543行+ 【playWithExternalPalyerEvent () 以及generateM3uFile（原generateDplFile）两个函数】
    playWithExternalPalyerEvent () {
      this.fetchM3u8List().then(m3u8Arr => {
        const fs = require('fs')
        var externalPlayer = this.setting.externalPlayer
        if (!fs.existsSync(externalPlayer)) {
          this.$message.error('请设置第三方播放器路径')
          // 在线播放该视频
          var link = 'https://www.m3u8play.com/?play=' + m3u8Arr[this.video.info.index]
          const open = require('open')
          open(link)
        } else {
          var exec = require('child_process').execFile
          var M3uFile = this.generateM3uFile(this.video.info.name, m3u8Arr, this.video.info.index)
          exec(externalPlayer, [M3uFile])
        }
      })
    },
    generateM3uFile (fileName, m3u8Arr, index) {
      const path = require('path')
      const os = require('os')
      const fs = require('fs')
      var filePath = path.join(os.tmpdir(), fileName + '.m3u')
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath)
      }
      var str = '#EXTM3U' + os.EOL

      var ind = 1
      m3u8Arr.forEach(element => {
        str += '#EXTINF:-1 ,' + '第' + ind + '集' + os.EOL
        str += element + os.EOL
        ind += 1
      })
      fs.writeFileSync(filePath, str)
      return filePath
    },

非程序员非编程学生，见谅， generateM3uFile (fileName, m3u8Arr, index) 此行后面两个参数应该是能删除的。

可以参考下。

**Comment by cuiocean** [comment]
多谢建议，确实dpl是potplayer专属格式，m3u格式会有更好的支持。代码已经check in
