### ISSUE TITLE
无搜索结果       的 通知挺烦人的  取消掉吧

### ISSUE THREAD

**Issue by hualuoshuijia** [Hunlongyu/ZY-Player#206]
这个通知取消掉吧，挺烦人的
![image](https://user-images.githubusercontent.com/49584289/91845325-85f11500-ec8b-11ea-857b-8b1a5d52122f.png)

**Comment by hualuoshuijia** [comment]
[原创工具] M3U8批量下载器 V1.4.5【7月9日更新】
https://www.52pojie.cn/thread-1216473-1-1.html



m3u8loader下载器
https://www.coolapk.com/apk/ru.yourok.m3u8loader（https://github.com/YouROK/m3u8）

这俩下载挺快的，您看是不是对软件有帮助，对于一些速度慢点资源网站，总是等缓存没耐心，希望软件更加完善

**Comment by cuiocean** [comment]
下个版本中,无所有结果提示会被取消掉.
