### ISSUE TITLE
不能播放到底是我的问题还是源的问题？

### ISSUE THREAD

**Issue by jxjxjhjh** [Hunlongyu/ZY-Player#209]
https://github.com/Hunlongyu/ZY-Player/issues/186
之前在这个帖子下反馈过，因为反馈的人不多，一直以为是我自己的问题，但刚才突然发现有的源可以播放了。

从上往下至少有10几个源都不能播放，无意中点了1886这个排名靠后的源，竟然可以播放了，而且速度很快。

zy2.3阶段就开始用，一开始挺好的，但是后来就出现无法播放的问题了，不是zy版本问题，之前试过很多zy版本都是这样的。
装vlc/ffmepg等软件都没用，后来就点第三方播放器播放，跳出m3u8文件地址，打开发现403，就怀疑是源播放地址问题，瞎搞终于找到了1886这个可以播放的源。

为什么没什么人反馈问题？

**Comment by buvta** [comment]
源没什么问题，建议检查下网络及其配置
