### ISSUE TITLE
manjaro gnome中zy的图标在任务栏不显示

### ISSUE THREAD

**Issue by jxjxjhjh** [Hunlongyu/ZY-Player#210]
其他程序都正常，就只有zy不显示，奇怪了。
zy在人物程序列表等各个地方都显示图标，就是在任务栏中不显示（以前用win的，下面（本来在上面的）这个叫任务栏，但好像Linux中不这么叫）

**Comment by SamLukeYes** [comment]
你不说我还没发现。刚才试了一下，将.desktop 文件中的 `StartupWMClass` 设为 `zy` 即可解决这个问题。
AUR 上的那个包是用的 appimage，应该是 appimage 中包含的那个.desktop 文件不规范。

**Comment by jxjxjhjh** [comment]
> 你不说我还没发现。刚才试了一下，将.desktop 文件中的 `StartupWMClass` 设为 `zy` 即可解决这个问题。我已经向 AUR 上 `zy-player-appimage` 的维护者反馈了这个问题，目前已经修复。

谢谢，可惜我已经回了WINDOWS，LINUX的毛病还是挺多的。

**Comment by yangcore** [comment]
> 你不说我还没发现。刚才试了一下，将.desktop 文件中的 `StartupWMClass` 设为 `zy` 即可解决这个问题。我已经向 AUR 上 `zy-player-appimage` 的维护者反馈了这个问题，目前已经修复。

最新版本又出现了，添加zy后好了，提醒一下
