### ISSUE TITLE
第三方播放器请求加入 IINA

### ISSUE THREAD

**Issue by L1cardo** [Hunlongyu/ZY-Player#211]
既然 m3u8 的播放链接能获取到，希望 Mac 端的第三方播放器能加入 IINA

**Comment by cuiocean** [comment]
现在可以自行输入播放器地址,但我没有Mac可以测试,希望工作.

**Comment by L1cardo** [comment]
@cuiocean Mac端无法选择应用程序

![image](https://user-images.githubusercontent.com/33802186/92419993-6e41f100-f1a3-11ea-9c33-2b0c1ed1962b.png)

**Comment by cuiocean** [comment]
请尝试2.4.6版本,直接编辑播放器路径

**Comment by L1cardo** [comment]
> 请尝试2.4.6版本,直接编辑播放器路径

发现以下几个 bug：
1. 输入播放器路径后，按下 enter 变成空白，并提示已经设置成功，不知是否真正成功（第 2 点）
2. 无法使用第三方播放器


![2020-09-12 16-17-54 2020-09-12 16_19_33](https://user-images.githubusercontent.com/33802186/92991106-cd8d6180-f513-11ea-9429-a4dfe58d3ee1.gif)

**Comment by L1cardo** [comment]
Mac 用户最常用的播放器为 IINA，安装率可以达到 50% 以上，而且 IINA 支持命令行启动并且播放，类似以下这种。
```bash
iina https://youku.cdn7-okzy.com/20200904/20640_2ade4805/index.m3u8
```
不知 zyplayer 现在是如何实现的，但是可以使用这种方式进行第三方播放器的支持

**Comment by L1cardo** [comment]
我看了一下代码，好像就是
```bash
软件名 播放链接
```
这种形式来实现第三方播放器的打开，但是 Mac 下没办法打开，应该是第三方播放器路径没有保存成功吧

**Comment by cuiocean** [comment]
现在是 软件路径 m3u文件 你确认一下iina是否支持m3u文件 如果不支持 下次可以改成m3u8链接

**Comment by L1cardo** [comment]
> 现在是 软件路径 m3u文件 你确认一下iina是否支持m3u文件 如果不支持 下次可以改成m3u8链接

支持的呀，只要是视频，就没有 iina 支持的

**Comment by L1cardo** [comment]
就算 iina 不支持，在终端运行 `软件路径 m3u文件` 以后iina 也应该打开才对
但是现在没有任何反应

**Comment by sarkrui** [comment]
@L1cardo 应该是你配置的第三方播放器路径有问题

```
/Applications/mpv.app/Contents/MacOS/mpv
```
```
/Applications/IINA.app/Contents/MacOS/iina-cli
```

亲测使用上述路径可在 2.4.6 版本 zy-player 导出播放，参见下方动图
![gif_temp](https://user-images.githubusercontent.com/14228455/93198067-c4d3a000-f74c-11ea-96a2-14def5c9dc80.gif)

**Comment by L1cardo** [comment]
@sarkrui 你这么一说，我恍然大悟！😂😂

**Comment by maboloshi** [comment]
@L1cardo 如果使用`brew cask install iina`的方式安装`IINA`的话 还可以设置第三方播放器路径为`/usr/local/bin/iina`
