### ISSUE TITLE
ubuntu20.04下snap包安装问题

### ISSUE THREAD

**Issue by honglongyu** [Hunlongyu/ZY-Player#212]
由于签名问题sudo snap install zy.......... snap --broken安装后，只要重启就打不开了，点击图标无反应，卸载重装后正常，但这样每次都要开机重装，才能使用，能否发布Ubuntu的deb包，目前系统使用appimage包

**Comment by Hunlongyu** [comment]
GitHub release 里有 AppImage 包的呀~

**Comment by honglongyu** [comment]
嗯,appimage格式一切正常使用.在出个deb格式就更好了 appimage 单文件格式是挺方便的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hunlongyu/ZY-Player"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 晚上6:55
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"START"<417658337@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] ubuntu20.04下snap包安装问题 (#212)





 
GitHub release 里有 AppImage 包的呀~
