### ISSUE TITLE
希望收藏夹里添加个功能

### ISSUE THREAD

**Issue by king4107** [Hunlongyu/ZY-Player#213]
希望收藏夹里能够自由拖动排序，和分组或分类功能，再添加个播放记录，比如上次看到第几集，目前最新第几集，这样的功能。可以把播放分享等使用鼠标右键里，希望最顶上添加标题，比如名称，类型，年月，视频源，播放记录，最新更新（可换源，源可多选和单选和全选功能），一键追剧更新。

**Comment by cuiocean** [comment]
好多需求! 现在已经支持拖曳排序.

**Comment by cuiocean** [comment]
2.4.6版本里已支持拖曳,表头,和观看至第几集的功能
