### ISSUE TITLE
安装最新版后打开一片空白？是哪里的问题呢？

### ISSUE THREAD

**Issue by jiyuquan** [Hunlongyu/ZY-Player#214]
![QQ截图20200908215815](https://user-images.githubusercontent.com/20588210/92487210-8ce5cd80-f21f-11ea-9611-80e3dc7906da.jpg)

**Comment by cuiocean** [comment]
重置一下呢？

**Comment by qcxl** [comment]
我是MacOS 10.14.6的系统 也出现了这个问题，我来解释一下怎么解决 我使用App Cleaner卸载已安装的旧版本zy player并看了下缓存和配置目录 手动再删除一下 ，然后再安装最新版本就OK了 ，直接替换安装是会出现无法加载数据的问题，怀疑是版本升级之后读取了原来旧版本的缓存数据导致加载失败。大家可以按照这个方式试一下 ，Windows 上也可以尝试找到应用程序安装目录卸载清除干净，再安装新版本。

**Comment by skysinger** [comment]
> 缓存和配置目录

请问能给出路径吗？我找到一些历史文件删了还是不行

**Comment by Nirvana-junhao** [comment]
我有同样的问题，windows10 最新的系统，装了最新的播放器就是白板了

**Comment by cuiocean** [comment]
windows版本可以尝试清空%AppData%/zy 文件夹

**Comment by alphaking2008** [comment]
删除数据后确实好了

**Comment by Nirvana-junhao** [comment]
我直接把所有跟zy有关的文件全部删除了，然后重启电脑，重新安装就好了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: alphaking2008<mailto:notifications@github.com>
发送时间: 2020年9月29日星期二 上午11:03
收件人: Hunlongyu/ZY-Player<mailto:ZY-Player@noreply.github.com>
抄送: Nirvana-junhao<mailto:jiacai.li@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [Hunlongyu/ZY-Player] 安装最新版后打开一片空白？是哪里的问题呢？ (#214)


删除数据后确实好了

―
