### ISSUE TITLE
教大家一个Mac添加第三方的方法，另外反馈一个2.4.6版本的问题

### ISSUE THREAD

**Issue by Darling-Lee** [Hunlongyu/ZY-Player#221]
软件默认只能指定执行文件，所以你可以把播放器APP内部的执行文件创建一个链接文件到其他地方，然后zy-player设定指定他就行了。比如举个例子，要设定IINA，那么就进应用程序文件夹内找到IINA.app，右击显示报内容，再打开里面Contents文件夹，然后会看到一个MacOS的文件夹，打开它。再把里面的IINA可执行文件创建一个链接（类似于windows的快捷方式）到其他地方例如文档文件夹下。再去ZY-Player选择这个创建出来的链接文件就可以了。

另外，2.4.6有个小问题用的好纠结啊，比如我在浏览最大资源网，找到一个想看的片，一看发现播放很卡或者不好看，我要回去再找。这时候一点回去，他就不能保持在我点播放之前的状态，而是回到了源列表的第一个重新加载内容。比如我在浏览某个源，看了一下某个剧我不想看了，回去我要继续往下浏览，这时就得重新选源，不断的滚轮下去才能到达我上次浏览到的地方。2.4.5没有这个问题，估计是增加了编辑源顺序的时候使得这个功能出现了这个小状况。

**Comment by cuiocean** [comment]
@Darling-Lee 我试了一下,2.4.6确实有此问题. 已解决.你可以自行编译或者等下一个版本发布.

**Comment by Darling-Lee** [comment]
好的，谢谢


| |
Lee
|
|
lonelybboylonely@163.com
|
签名由网易邮箱大师定制
在2020年9月13日 14:20，cuiocean<notifications@github.com> 写道：

@Darling-Lee 我试了一下,2.4.6确实有此问题. 已解决.你可以自行编译或者等下一个版本发布.
