### ISSUE TITLE
关于分类匹配的建议

### ISSUE THREAD

**Issue by FreeGAV** [Hunlongyu/ZY-Player#223]
资源站分类都在CLASS中  分类没有一个很好的区分

1.直接屏蔽主分类
var type=["电影”，“电视剧”，“综艺”....];

if （name=type[1]）{
      // 不添加主分类
}

2. 规则匹配
var Movie=[];
var TV=[];
if （name=“动作片”）{
      Movie.push(nanme）
}
if （name=“连续剧”）{
      TV.push(nanme）      
}

3. 对某些资源限制  flag=福利资源选项
bool flag = true;
if （flag）{
     flag=true;
     //添加福利分类
}els{   
     flag=false;
   //不添加福利分类
}

**Comment by supbose** [comment]
看的就是福利。哈哈！！！到底改屏蔽谁：）

**Comment by cuiocean** [comment]
@supbose  还是有人需要屏蔽福利片的,😄. 应需求已经添加,不过只是在分类列表里面屏蔽了一些关键词而已. 最新列表里如果有福利的,那就时真福利了.

**Comment by cuiocean** [comment]
主分类也被屏蔽了.
