### ISSUE TITLE
请问有没有安卓的版本，谢谢

### ISSUE THREAD

**Issue by wy1ng** [Hunlongyu/ZY-Player#227]
一直在办公室用PC版的，突然有天想在手机上看，想起来ZYP号称是跨平台，然而并没有手机版的。。。
大家能给推荐下好用的安卓看片APP吗，谢谢~

**Comment by cxbcxj** [comment]
有这就是
https://github.com/vicedev/ZY-Player-Android.git

**Comment by ssylb0309** [comment]
有TV版就好了

**Comment by wy1ng** [comment]
> 有
> https://github.com/vicedev/ZY-Player-Android
> https://github.com/xiaojia21190/ZY_Player_flutter

感谢！

**Comment by wy1ng** [comment]
已解决
