### ISSUE TITLE
调用本地播放器功能

### ISSUE THREAD

**Issue by nlxtw** [Hunlongyu/ZY-Player#23]
有些视频质量不佳，要是能开发个调用本地播放器功能就相当完美了，目前还没发现哪个开发者开发了这种，估计难度较大吧......

**Comment by Hunlongyu** [comment]
1. 如果视频不佳, 即使本地播放器,类似: Potplayer, 优化也不会很明显.
2. 直接调用可能会有点复杂, 但是复制播放链接, 然后自己粘贴播放, 这样的简单功能还是可以实现的.
3. 不过这样的功能, zy player 下个版本应该不会加上的, 如果需求多的话, 我会考虑的.
