### ISSUE TITLE
更新到新版本后无法使用

### ISSUE THREAD

**Issue by diermozu** [Hunlongyu/ZY-Player#231]
在更新到新版本后，无法显示资源网站，左上的框框没有内容。无法搜索资源，右上的框框没有反应。
卸载重装后仍然如此。

**Comment by jiangfu204** [comment]
我也是

**Comment by cuiocean** [comment]
Windows下,请清理 AppData\Roaming\zy文件夹,再重试.

**Comment by easonzhang1992** [comment]
C:\Users\Administrator\AppData\Roaming\zy 文件夹删除掉即可
