### ISSUE TITLE
建议增加加载/搜索状态提示

### ISSUE THREAD

**Issue by vii912** [Hunlongyu/ZY-Player#234]
在高峰期或者网速不好的时候搜索，经常误以为操作失误甚至电脑/手机卡了，因为搜索之后，直到结果出来之前，整个界面没有任何提示！
so，虽然不是功能上的BUG，但使用体验上确是非常致命，希望能早日改善这方面体验。

**Comment by cuiocean** [comment]
2.3.8修复bug时 已设置搜索的timeout为2秒 所以如果2秒内没有返回搜索结果的话就自动结束了 变相的解决了你的问题
