### ISSUE TITLE
有没有交流群呢

### ISSUE THREAD

**Issue by IDjunlin** [Hunlongyu/ZY-Player#235]

**Comment by Hunlongyu** [comment]
![image](https://user-images.githubusercontent.com/15273630/94353351-d5680c80-00a2-11eb-9203-5f20f53dff3e.png)

**Comment by moobyes** [comment]
超过200人了

**Comment by Hunlongyu** [comment]
嗯嗯 超过2百人, 就无法扫码入群了呢. 这个是新的二群呢, 有兴趣可以扫码进入哈
[image: image.png]

木白 <notifications@github.com> 于2020年9月28日周一 上午10:55写道：

**Comment by Hunlongyu** [comment]
![image](https://user-images.githubusercontent.com/15273630/94389075-68777400-0181-11eb-89aa-b544b0a3622f.png)
二群
