### ISSUE TITLE
屏幕闪动啊

### ISSUE THREAD

**Issue by arthur1976** [Hunlongyu/ZY-Player#236]
每次点击 进入全拼 就会闪动啊 你们没发现吗

**Comment by cuiocean** [comment]
没有发现. 请提供更详细的重现步骤

**Comment by arthur1976** [comment]
哦。我刚才又试了一下 发现看别的电视电影没事 ，只有看电视剧：沉没的真相 时，点击屏幕右下角的进入全屏后&nbsp; 就会出现进度条和标题 剧烈闪动。。。也许是个别现象吧





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hunlongyu/ZY-Player"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月28日(星期一) 晚上10:50
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"Wyeth"<www.wyeth@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] 屏幕闪动啊 (#236)





 
没有发现. 请提供更详细的重现步骤
