### ISSUE TITLE
✨🎉 内测版本反馈 🎊🎇

### ISSUE THREAD

**Issue by Hunlongyu** [Hunlongyu/ZY-Player#24]
#### 本次版本新增特色和功能:
1. 全平台支持. windows, mac, linux.
2. 新增多个视频源. 未来更新更多的视频源.
3. 新增历史播放记录, 并且会自动记录播放进度. 
4. 新增分享功能. 一键分享海报图片.
5. 新增精简模式. 主要用来上班划水的. 支持修改透明度.
6. 全新布局配色.
7. 新增多语言. 
8. 下载功能 (最大资源网和OK资源网支持下载.)
9. 更详细的视频分类
10. 收藏夹同步更新视频追剧.(手动更新)
11. 新增支持Win32位系统
12. 后台自动更新
...

#### 下载链接: 
1. Github: https://github.com/Hunlongyu/ZY-Player/releases

#### 截图:
![001.png](https://i.loli.net/2020/04/28/T3YZvStwNQJ5aHy.png)
![003.png](https://i.loli.net/2020/04/28/2xYw9nIyWSZ5Rsr.png)

还有很多网友建议的功能没有开发. 目前主要以软件的核心功能为主.先让软件能够运行起来. 当然网友建议的功能我都有记录下来. 以后有时间我会慢慢补充上去.

大家可以在这里反馈新版的使用体验. 以及使用过程中的Bug.

建议大家根据模板来, 这样我能更好的定位问题,及时解决:

系统: windows
版本: v0.9.x
问题: 无法播放
截图: 🖼

**Comment by warden22** [comment]
15版本搜索资源不方便，切换播放源不能自动列出对应资源，需要每次回车一下，之前的OK资源网呢?
皮肤怎么没有绿色，绿色有益于眼睛，黑白伤眼。。。
新的下载功能不错，资源收藏者的福音。。。
其它问题暂时没怎么看，后期再提交，作者辛苦了。

**Comment by Hunlongyu** [comment]
@warden22 
1. 搜索资源的问题已经注意到了,下个版本会修复.
2. OK资源网 我这边经常播放失败, 就删除了. 如果大家之前的老版本的OK资源网还可以用的话,下个版本我会加上.
3. 这个是测试版, 主要以核心功能为主, 更多主题, 以及更多视频源会在以后更新添加.

**Comment by Hunlongyu** [comment]
## 20200430  更新日志: 
### v0.9.16
1. 新增支持Windows 32位系统
2. 优化搜索逻辑
3. 新增 OK资源网, 支持下载. (我这边播放失败, 所以放到最后了.)
4. 修复自动播放下一集时, 会播放下下一集的Bug.

**Comment by heyzayz** [comment]
是否可以可以切换成有海报图预览，鼠标滞留显示电视或电影简介

**Comment by warden22** [comment]
@Hunlongyu 新BUG
系统：WIN10 64 家庭版
版本：16
描述：自动下一集时，直接跳到29分钟，比如一个45分钟的电视，自动下一集后从29分钟开始播放

**Comment by warden22** [comment]
1909的

**Comment by xu93nuo1987** [comment]
0.9.16 设置 点 官网 在原窗口打开官网后左侧按钮消失，放大缩小和关闭窗口的按钮也消失了！

**Comment by Hunlongyu** [comment]
## 20200507 更新日志: 
### v0.9.18
1. 新增绿色护眼主题
2. 修复自动播放下一集时，播放进度错误的问题
3. 修复点击官网和反馈时，不使用默认浏览器打开的问题

**Comment by xu93nuo1987** [comment]
209资源网没有内容反馈，http://www.209zy.com/可能网站挂了！

**Comment by xu93nuo1987** [comment]
18版， 209资源网没有内容反馈，http://www.209zy.com/可能网站挂了！
点击新的视频播放时显示以前视频停止或者播放画面，建议新播放切换换面不显示上一视频画面。
切换到精简模式后，精简模式没有返回原模式按钮，只能点击关闭。返回原模式没有精简模式播放记录和播放到了多少分钟，也不能继续播放！ 
建议在设置有版本号显示！

**Comment by warden22** [comment]
这个绿色太难看了，就换成应用LOG那个底色就可以，青色？就是跟0.9.1一样的主题，那个颜色看得舒服

**Comment by warden22** [comment]
估计大佬快被逼疯了，有众多网友帮忙内测提交BUG。。。。

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
1. 有些资源网站会间歇性的出问题,有可能是网站维护,也有可能是网络问题. 可以暂时先切换到其他视频源.
2. 切换视频我会在下一个版本增加 Loading 界面
3. 精简模式 确实还存在很多问题. 当初没想到会这么复杂的. 我会在后续几个版本优化.
4. 会在设置里添加版本号

@warden22 
1. 这个绿色主题我后期会优化.

**Comment by Hunlongyu** [comment]
@warden22 
😂 没事的, 我还挺得住.
主要公司的工作最近挺忙的, 老板还想让我们加班. 
所以最近没有出新功能, 主要以修复 bug 为主.

**Comment by Hunlongyu** [comment]
## 20200507 更新日志: 
### v0.9.25
1. 从 v0.9.25 版本开始，以后每个版本不需要手动下载，软件会自动更新
2. 修复手动点击下一集时，播放进度错误的问题
3. 新增切换视频时的 Loading 界面

**Comment by xu93nuo1987** [comment]
v0.9.25 切换视频时的 Loading 界面 感觉背景颜色单调，建议能否以徽标做背景显示!
            建议添加个能全资源搜索的页面或者按钮,不过估计搜索速度会很慢！

**Comment by xu93nuo1987** [comment]
v0.9.29 切换视频时的 Loading 界面 感觉背景颜色单调，建议能否以徽标做背景显示!
            建议添加个能全资源搜索的页面或者按钮，每个资源打开搜索的确有点难找，不过估计搜索速度会很慢！

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
1. 切换视频的 Loading 确实过于简单粗暴了, 后期会优化, 不过就不用 Logo 了. 新版 logo 有点花哨. 不能适配所有的主题皮肤.
2. 一键全视频源搜索, 短期内不会考虑. 主要是资源重复率高, 排名靠前的视频源资源最多. 如果前面的搜不到,后面的几乎也都没有. 当然我会记录在开发计划里. 后期有时间我会完善的.
3. 目前官网还没有开发, 所以新功能暂时都不会进行. 但会修复一些 bug.

**Comment by heyzayz** [comment]
原来的 小窗口全屏挺好用的  还能再有吗

**Comment by xu93nuo1987** [comment]
v0.9.29 win10 软件升级不成功，不知道是不是我的安装路径修改过的问题，还是升级出现问题，导致双击打开没有反应也没提示！ 无v0.9.29安装包不能测试！
v0.9.30 播放连续剧时切换到小窗口，如20集15分钟，关闭小窗口后在正常窗口历史记录播放时是20级15分钟播放，但是，如果选集21,22,23就会在15分钟开始播放，如果用下一集按钮就会正常从0分钟开始！

**Comment by xu93nuo1987** [comment]
v0.9.29 win10 软件升级不成功，不知道是不是我的安装路径修改过的问题，还是升级出现问题，导致双击打开没有反应也没提示！ 无v0.9.29安装包不能测试！
v0.9.30 播放连续剧时切换到小窗口，如20集15分钟，关闭小窗口后在正常窗口历史记录播放时是20级15分钟播放，但是，如果在播放列表选集21,22,23就会在15分钟开始播放，如果用下一集按钮就会正常从0分钟开始！

**Comment by Hunlongyu** [comment]
@heyzayz 
小窗口全屏加回来了, 但是因为限制修改软件尺寸, 所以并没有以前好用, 后期我会尽力完善现在的精简模式, 期望能更好用.

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
感谢大兄弟帮忙测试.
1. 我这边测试发现,如果安装的时候, 选择 给所有人, 就会升级失败. 如果选择给自己用, 就能升级成功.
1.1 我猜测, 给所有人用的时候, 会获取管理员权限.但是自动升级的时候, 软件没有使用管理员权限打开, 导致升级失败.
1.2 升级的原理是,先卸载老版本的软件, 然后安装新版本. 但是因为权限问题, 卸载了老版本, 却无法安装新版本, 导致软件都启动不了.
1.3 这边建议安装的时候,选择给自己使用. 安装路径应该是不影响升级的.
2. 播放进度已经修复, 下个版本放出.

**Comment by wclnmz666** [comment]
系统: windows
版本: 1909
问题：每次在窗口全屏和全屏模式的时候，刚开始的时候想拉进度条，在最前面的一小部分只要光标移动到那里进度条就消失了，很烦人，以前的版本也都会这样

**Comment by Hunlongyu** [comment]
@wclnmz666 
1. 我这边测试没有问题, 我初步猜测是显示器高分辨率的问题.
1.1 你用的什么分辨率的显示器
![Snipaste_2020-05-09_11-03-25.png](https://i.loli.net/2020/05/09/S1n2HX3D5UPadVR.png)
1.2 截图这个我看看.

**Comment by wclnmz666** [comment]
@Hunlongyu 我也就是普通的1080p分辨率，24寸，16：9的显示器

**Comment by kaixina485** [comment]
为什么有了内测版以前的老版就打不开了，，，我以前的上面收藏了好多电视呢，，，也没有办法弄出来

**Comment by kaixina485** [comment]
为什么会自动更新呢，，，还是觉得老版的好用点

**Comment by Hunlongyu** [comment]
@kaixina485 
1. 因为内测快结束了, 而同一个软件, 只是版本更新自然会覆盖以前的版本.
2. 很抱歉没有通知大家.给大家造成损失
3. 如果可以的话, 加我微信: (hunlongyu   备注: zyplayer 恢复数据) 我可以远程尝试帮你恢复一下数据.

**Comment by kaixina485** [comment]
谢谢您，，我没有责怪的意思,就是想问一下，因为昨晚在老版看完之后就自动下载了新版，然后老板也进不去了，所以就是想来问一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hunlongyu"; 
发送时间: 2020年5月11日(星期一) 上午9:26
收件人: "Hunlongyu/ZY-Player";
抄送: "kaixina485"<1009379679@qq.com>;"Mention";
主题: Re: [Hunlongyu/ZY-Player] &#x2728;&#x1F389; 内测版本反馈 &#x1F38A;&#x1F387; (#24)





 
@kaixina485
  
因为内测快结束了, 而同一个软件, 只是版本更新自然会覆盖以前的版本.
 
很抱歉没有通知大家.给大家造成损失
 
如果可以的话, 加我微信: (hunlongyu   备注: zyplayer 恢复数据) 我可以远程尝试帮你恢复一下数据.
  
&mdash;

**Comment by Hunlongyu** [comment]
@kaixina485 
1. 😂没事的, 我这边做了相关代码以确保不会丢失数据. 但是因为太忙, 忘记了测试. 所以还是出错了, 确实不应该.
2. 更新后, 新版本可以使用么? 如果新版本有什么问题, 可以直接提出

**Comment by kaixina485** [comment]
更新后可以使用，但是还是有些不习惯，最主要就是我收藏的那些视频，然后还有观看的进度啥的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 上午9:50
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"王博"<1009379679@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] ✨🎉 内测版本反馈 🎊🎇 (#24)





 
@kaixina485
  
😂没事的, 我这边做了相关代码以确保不会丢失数据. 但是因为太忙, 忘记了测试. 所以还是出错了, 确实不应该.
 
更新后, 新版本可以使用么? 如果新版本有什么问题, 可以直接提出

**Comment by kaixina485** [comment]
还有一个事情，OK资源网的资源我觉得是最全的，但是好像使用体验不是太好，有时候会加载不出来显示超时，不知道是网站本身原因还是什么




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 上午9:50
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"王博"<1009379679@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] ✨🎉 内测版本反馈 🎊🎇 (#24)





 
@kaixina485
  
😂没事的, 我这边做了相关代码以确保不会丢失数据. 但是因为太忙, 忘记了测试. 所以还是出错了, 确实不应该.
 
更新后, 新版本可以使用么? 如果新版本有什么问题, 可以直接提出

**Comment by Hunlongyu** [comment]
@kaixina485 
1. 观看进度有什么问题么? 现在有历史记录和历史播放进度. 所以看过的视频,并不是从头开始播放.
2. 最大资源网 和 OK资源网 目前是全网最全的两个资源网. 所以被很多爬虫爬取资源, 目前网上大部分的视频在线播放网站, 用的资源就是这两个. 所以我猜测这些资源网做了一些限制. 
3. 如果资源无法加载和视频无法播放, 基本上都可以确定是该资源网出了问题. 这个时候还是换个资源网试一试吧.

**Comment by kaixina485** [comment]
好的好的，麻烦了------------------ 原始邮件 ------------------
发件人: "Hunlongyu"<notifications@github.com>
发送时间: 2020年5月11日(星期一) 上午10:24
收件人: "Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com>;
抄送: "kaixina485"<1009379679@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Hunlongyu/ZY-Player] &#x2728;&#x1F389; 内测版本反馈 &#x1F38A;&#x1F387; (#24)




 
@kaixina485
  
观看进度有什么问题么? 现在有历史记录和历史播放进度. 所以看过的视频,并不是从头开始播放.
 
最大资源网 和 OK资源网 目前是全网最全的两个资源网. 所以被很多爬虫爬取资源, 目前网上大部分的视频在线播放网站, 用的资源就是这两个. 所以我猜测这些资源网做了一些限制.
 
如果资源无法加载和视频无法播放, 基本上都可以确定是该资源网出了问题. 这个时候还是换个资源网试一试吧.
  
&mdash;

**Comment by xu93nuo1987** [comment]
0.9.31我的今天怎么迟迟不能自动更新到0.9.32呢！

**Comment by xu93nuo1987** [comment]
0.9.32播放视频时→进入样式全屏→进入全屏→ESC/点击退出全屏   退回窗口异常显示，不能显示图像!

**Comment by xu93nuo1987** [comment]
精简模式左上角的5-100那个可以调整数字的那个是什么功能啊，一直没琢磨明白！

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
1. 全屏问题,下个版本尝试修复.
2. 精简模式里5-100 是透明度. 主要用于上班划水, 透明度低一般人不盯着屏幕看不到.使用方法: 输入数字按回车键.

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
1. 0.9.33 版本已放出, 修复全屏问题
2. 精简模式之前一直是失效的, 因为最近太忙一直没有划水. 所以没有发现. 33 版本已修复.

**Comment by Hunlongyu** [comment]
😘
![01.gif](https://i.loli.net/2020/05/12/oHv1xhfmDszykaJ.gif)

**Comment by xu93nuo1987** [comment]
我是win10一直就没实现透明哦！

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
升级到 0.9.33 版本还不行么?

**Comment by xu93nuo1987** [comment]
可以了！

**Comment by xu93nuo1987** [comment]
0.9.33 可以了！

**Comment by kaixina485** [comment]
想问一下，0.8.9是不是不支持历史记录和历史播放记录啊

**Comment by xu93nuo1987** [comment]
简易版偶尔暂停就出现失效，刷新不了，有时一暂停就重新播放了！

**Comment by xu93nuo1987** [comment]
简易版偶尔暂停就出现失效，刷新不了，有时一暂停就重新播放了！有时不能自动下一集！

**Comment by Hunlongyu** [comment]
@kaixina485 
0.8.9 的版本太老了, 只有最新版才有历史记录. 现在还是内测 0.9.x, 正式版将是 v1.0.0

**Comment by kaixina485** [comment]
好的好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月12日(星期二) 下午3:14
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"王博"<1009379679@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] ✨🎉 内测版本反馈 🎊🎇 (#24)





 
@kaixina485
 0.8.9 的版本太老了, 只有最新版才有历史记录. 现在还是内测 0.9.x, 正式版将是 v1.0.0

**Comment by kaixina485** [comment]
那个，，，为什么我这个最新版没有历史播放记录。我收藏的时候看到了207集，然后我现在看到了217集，为什么下次打开还是会从207集开始啊

**Comment by 99352qq** [comment]
为什么有时候最新资源网加载不出来，有的怎么播放不了，比如最新资源网天师斗妖姬，分享扫码能观看，电脑上不行，还有这个软件没有IPAD版吗

**Comment by Hunlongyu** [comment]
@kaixina485 
精简模式下观看, 是没有历史记录的. 最近有点忙, 所以这块功能没有完善. 整个软件也就这块没有完善所以一直属于内测版. 等这块完善后, 就发版正式版了.

**Comment by Hunlongyu** [comment]
@99352qq 
1. 资源网加载不出来内容, 或者无法播放, 请切换到其他视频源搜索播放. 
2. 至于为什么, 可能是因为访问过于频繁, 被相应的资源屏蔽了.也有可能是资源网服务器波动不稳定.
3. 资源内容 和 播放的视频, 没有正相关. 有可能能加载资源内容却无法播放.
4. IPAD 短期内没有开发计划, 未来说不定.

**Comment by kaixina485** [comment]
我不是用的精简模式，就是正常的那个模式。历史记录和历史播放记录都不行，上上个版本好像可以，会记录你看到了哪一集


 
 
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 上午9:03
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"王博"<1009379679@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] ✨🎉 内测版本反馈 🎊🎇 (#24)





 
@kaixina485
 精简模式下观看, 是没有历史记录的. 最近有点忙, 所以这块功能没有完善. 整个软件也就这块没有完善所以一直属于内测版. 等这块完善后, 就发版正式版了.

**Comment by Hunlongyu** [comment]
@kaixina485 
我这边测试可以, 我猜测是不是因为你是老版本升级来的. 导致数据库有问题. 你试试卸载软件重装. 我这边开发一个重置数据库功能.看看能不能解决各种数据库的问题.

**Comment by kaixina485** [comment]
好的好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 上午9:48
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"王博"<1009379679@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] ✨🎉 内测版本反馈 🎊🎇 (#24)





 
@kaixina485
 我这边测试可以, 我猜测是不是因为你是老版本升级来的. 导致数据库有问题. 你试试卸载软件重装. 我这边开发一个重置数据库功能.看看能不能解决各种数据库的问题.

**Comment by warden22** [comment]
韩大佬，
刚有个主意，麻烦采纳一下，增加到软件第四期开发中去。
1.添加直播源，央视全套+地方卫视+海外电视+直播（斗鱼，虎牙等，直播板块可选，也可不考虑）
2.添加音乐播放，支持网易云音乐，QQ音乐等知名站点的全站搜索试听，下载（有版权的能破解最好）
3.添加一些知名网站消息订阅，如少数派，小众软件，月光博客等
4.添加京东，天猫等内部优惠券返利信息等（可选）
5.能将软件搜索到的资源一键离线到百度网盘，天翼云盘。


以上请酌情考虑，可能要求提太多了哈。
















在 2020-05-13 09:48:55，"kaixina485" <notifications@github.com> 写道：

好的好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 上午9:48
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"王博"<1009379679@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] ✨ 内测版本反馈 (#24)






@kaixina485
我这边测试可以, 我猜测是不是因为你是老版本升级来的. 导致数据库有问题. 你试试卸载软件重装. 我这边开发一个重置数据库功能.看看能不能解决各种数据库的问题.

**Comment by kaixina485** [comment]
我卸载了又重新装的还是不行

**Comment by Hunlongyu** [comment]
@kaixina485 
我这边刚刚优化了一下, 添加了重置软件的功能. 会删除数据库. 

我发现卸载貌似并不能完全清理相关数据. 包括数据库.

等我发布了, 你再试试😂

![Snipaste_2020-05-13_11-48-37.png](https://i.loli.net/2020/05/13/wtuRHdlbZoO97kE.png)

**Comment by kaixina485** [comment]
好的，麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 中午11:50
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"王博"<1009379679@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] ✨🎉 内测版本反馈 🎊🎇 (#24)





 
@kaixina485
 我这边刚刚优化了一下, 添加了重置软件的功能. 会删除数据库.
 
我发现卸载貌似并不能完全清理相关数据. 包括数据库.
 
等我发布了, 你再试试😂

**Comment by Hunlongyu** [comment]
@warden22 
1. 里面的每一个功能拿出来, 都能单独做一个软件.😂
2. 而且优惠卷什么的和播放器也没有什么联系.
3. 其实我的 Idea 表里,有很多想法, 但是时间不够呀.
4. 作为一个程序员, 这个软件,只是练手用的, 这么长时间了, 我自认为差不多了. 该攻克其他方向了. 比如做个移动端的播放器.

**Comment by xu93nuo1987** [comment]
win10 软件升级前有个提示，是全英文的，能否改成中文啊！

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
1. 尝试修改了一下,没有成功, 可以改成无提示, 后来想想还是提示吧. 所以暂不修改.

**Comment by kaixina485** [comment]
大哥，为啥那个历史记录还是不行啊，我重置了也不行，是我这边的问题吗😭

**Comment by Hunlongyu** [comment]
@kaixina485 
我再看看

**Comment by youlikejohn** [comment]
0.9.33播放界面偶尔会卡按钮，鼠标点击没有任何反应，比如选集，历史等按钮卡死。其他3个界面操作正常

**Comment by kaixina485** [comment]
我今天才知道历史记录怎么用😂麻烦啦麻烦啦



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 上午9:43
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"王博"<1009379679@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] ✨🎉 内测版本反馈 🎊🎇 (#24)





 
@kaixina485
 我再看看

**Comment by undefined-xx** [comment]
我安装的时候一直提示我安装已终止，安装程序并未成功的运行完成，怎么搞哦
