### ISSUE TITLE
强烈建议加上直播源

### ISSUE THREAD

**Issue by arthur1976** [Hunlongyu/ZY-Player#242]
建议资源里加上直播源啊 ，起码央视的加上

**Comment by arthur1976** [comment]
。。。。。。。。。。。。。。。。。。我不是大佬啊  我是建议啊 可以把黑鸟播放器的偷过来用啊

**Comment by cuiocean** [comment]
:) 我知道. 那些播放器都不提供后台在线直播的源啊. 我找了几个,有的还可以.如果有谁能提供央视的源的话,我就不需要自己去慢慢搜了.

**Comment by arthur1976** [comment]
哦哦，不懂原来这么复杂啊。。。

**Comment by duansheli** [comment]
@cuiocean 
这项目没提供安装包 需要自己打包
https://github.com/parzulpan/real-live 
你可以找找有没有直播源的配置文件

**Comment by buvta** [comment]
imDazui/Tvlist-awesome-m3u-m3u8 [CCTV+卫视-腾讯云](https://raw.githubusercontent.com/billy21/Tvlist-awesome-m3u-m3u8/master/m3u/%E8%85%BE%E8%AE%AF%E4%BA%91.m3u)效果不错，直接用vlc就行，有必要吗？

**Comment by cuiocean** [comment]
多谢提供数据,我已可以实现在ZY Player内部播放直播.内置源为腾讯云的源,支持从m3u导入新源.
![image](https://user-images.githubusercontent.com/5760235/95012982-5c862900-063d-11eb-8283-21a25cf1844d.png)

**Comment by buvta** [comment]
不客气，再建议用[vue drag tree table](https://github.com/mafengwo/vue-drag-tree-table)替换vuedraggable实现分组

**Comment by cuiocean** [comment]
嗯，后续可以考虑
