### ISSUE TITLE
爱死你了

### ISSUE THREAD

**Issue by arthur1976** [Hunlongyu/ZY-Player#249]
哈哈 真加直播源了啊 我还以为你不会把我建议当回事呢，太好了。这样只安装你这一个播放器就能看所有想看的了。他那个黑鸟播放器就没优势了

**Comment by cuiocean** [comment]
😊

**Comment by singlering** [comment]
> 哈哈 真加直播源了啊 我还以为你不会把我建议当回事呢，太好了。这样只安装你这一个播放器就能看所有想看的了。他那个黑鸟播放器就没优势了

有直播源推荐吗
