### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by iam3ddy** [Hunlongyu/ZY-Player#25]
error when closing the app
![Screenshot 2020-05-08 at 9 27 22 AM☀️](https://user-images.githubusercontent.com/21017389/81360362-33a14c80-910e-11ea-9a55-7db19ed7a304.png)

**Comment by Hunlongyu** [comment]
我没有Mac 电脑, 所以我没法调试解决. 如果播放功能没有影响, 暂且忍耐一下吧, 我会尽力修复的.😥

**Comment by iam3ddy** [comment]
没事。辛苦了

**Comment by JIACHENG135** [comment]
> 没事。辛苦了

您好,Mac用户可以考虑下我最近开发的JCPlayer, 最近一星期开始写的,欢迎试用提issue,感谢!
[主页](https://jcplayer.me)
[Github](https://github.com/JIACHENG135/JCPlayer)
