### ISSUE TITLE
屏蔽福利片

### ISSUE THREAD

**Issue by singlering** [Hunlongyu/ZY-Player#251]
1. 屏蔽福利片的勾选去掉后，没反应
每次重启，默认又勾选了“屏蔽福利片”

2. 第三方播放，添加了本地播放器，怎么使用？

**Comment by cuiocean** [comment]
第一个问题已解决,请等待下一个release. 第二个问题,在播放页面,右上角,有按钮,在第三方播放器打开
![image](https://user-images.githubusercontent.com/5760235/95093354-f971c080-0728-11eb-9c2a-b128645e5f2a.png)

**Comment by singlering** [comment]
收到 谢谢
