### ISSUE TITLE
交流群求拉

### ISSUE THREAD

**Issue by singlering** [Hunlongyu/ZY-Player#252]
交流群昨天失效了

**Comment by cuiocean** [comment]
![Uploading 5BF129CC-93E7-4BB1-AED3-E9B25F2413EB.jpeg…]()

**Comment by cuiocean** [comment]
![6F936ADE-DA81-4349-99CB-B047CD69E215](https://user-images.githubusercontent.com/5760235/95181118-27a3de80-07c3-11eb-86d4-967db70cd2e2.jpeg)

**Comment by cuiocean** [comment]
可以加入QQ交流群，群文件里有最细安装包
![image](https://user-images.githubusercontent.com/5760235/95768524-c8f4ce00-0cb6-11eb-8646-0b6bc5fe47a0.png)
