### ISSUE TITLE
电影分类里的屏蔽

### ISSUE THREAD

**Issue by YuanHsing** [Hunlongyu/ZY-Player#255]
2.4.7
更新日志:
4.电影分类里屏蔽了 '电影', '电影片', '电视剧', '连续剧', '综艺', '动漫' 等主分类
--------------------------------------------------------------------------
建议是否可以把以上的屏蔽改为让使用者可以在设定里打勾选取屏蔽？

因为我经常使用的网站为「永久资源」里的「动漫」
但是「永久资源」里没有像「ok资源网」一样，屏蔽了「动漫」分类，还有子分类「国产动漫、日韩动漫、欧美动漫」可以选，所以导致永久资源的「动漫」就消失了！
但是之前永久资源收藏的动漫还在。

谢谢

**Comment by cuiocean** [comment]
已添加该设置,请等待下一版本更新
