### ISSUE TITLE
小小建议，

### ISSUE THREAD

**Issue by hualuoshuijia** [Hunlongyu/ZY-Player#256]
播放列表和播放历史  需要点击才能显示，不能像音量似的，鼠标指到上面就显示，

![image](https://user-images.githubusercontent.com/49584289/95328464-2c0deb80-08d8-11eb-886e-672fed745ec9.png)

![Uploading image.png…]()

**Comment by buvta** [comment]
点击相当于确认，音量不怎么占用显示面积体验影响不大

**Comment by buvta** [comment]
IPTV在迷你模式下不可用，建议将正在直播移到“next”后面，还有电视模式下播放列表改为频道列表，左边上下切换改为切换频道

**Comment by buvta** [comment]
迷你模式标题条自动隐藏，聚焦时才显示

**Comment by cuiocean** [comment]
这个属于个人喜好问题,多谢建议,但不会开发该功能.
