### ISSUE TITLE
希望影视的：分类项 能做详细一点吗

### ISSUE THREAD

**Issue by Viktor20999** [Hunlongyu/ZY-Player#261]
套用网页版的搜索项目：影视类型，时间，国家等！~~不然只能知道电影名字才能搜索呢~~想找某一类的比较麻烦嗯！

**Comment by cuiocean** [comment]
或许分类就是你想要的功能？搜索时间，国家，演员名字等功能，需要API支持才行。目前只支持搜索名字。
![image](https://user-images.githubusercontent.com/5760235/95452620-d124d480-0969-11eb-8129-163f6c18f3d0.png)
