### ISSUE TITLE
播放比例问题

### ISSUE THREAD

**Issue by mxhx** [Hunlongyu/ZY-Player#263]
您好，播放画面比例可否增加16:9, 4:3选项，有些视频看着是被拉宽，有的是拉长。

**Comment by mxhx** [comment]
勾选了搜索所有资源，但不稳，经常只搜索默认的那个资源网内容。
还有搜索结果返回主页要把走索内容删完才行。

**Comment by cuiocean** [comment]
视频比例不对的话,应该是视频源的问题.建议用第三方播放器,比如PotPlayer打开, 然后就可以调整图像比例了.

**Comment by cuiocean** [comment]
关于搜索所有资源,我这里用起来没有问题.请升级到最新版2.5.2.1
