### ISSUE TITLE
越来越喜欢了

### ISSUE THREAD

**Issue by arthur1976** [Hunlongyu/ZY-Player#264]
越来越喜欢这个播放器了加了直播源就是好 ，设置里新加的闭屏主分类我么搞懂是什么意思啊

**Comment by cuiocean** [comment]
:). 那个是好多源的主分类,比如电影,电视剧,动漫等,下面的内容为空,真正的内容放在子分类下.之前设置为默认都过滤掉的,但有人反映,有些源主分类下也有内容. 所以就弄了个开关.
