### ISSUE TITLE
关于播放器播放电影的声音问题

### ISSUE THREAD

**Issue by sugarnine9** [Hunlongyu/ZY-Player#266]
用了很久，感觉一直存在的问题就是播放声音太小了啊？
正常电脑只要调到30左右就能听的很清晰了，有时候这个软件要调到90-100才能听的清，请问这是个啥问题？

**Comment by Hunlongyu** [comment]
每个软件的音量都不一样呢,可以手动调节试一试.
![image](https://user-images.githubusercontent.com/15273630/95646778-63f67800-0afe-11eb-903d-30d3c97e147e.png)

**Comment by sugarnine9** [comment]
> 每个软件的音量都不一样呢,可以手动调节试一试.
> ![image](https://user-images.githubusercontent.com/15273630/95646778-63f67800-0afe-11eb-903d-30d3c97e147e.png)

emmm，我是在说zy player呀。用它播放声音好小，你们没有这样吗。我是dell的win10 1907，用ZY Player播放的时候一般要调到90左右才能听得清，一般用Pot player20左右就够了。T T

**Comment by sugarnine9** [comment]
> 每个软件的音量都不一样呢,可以手动调节试一试.
> ![image](https://user-images.githubusercontent.com/15273630/95646778-63f67800-0afe-11eb-903d-30d3c97e147e.png)
试了一下，好像是不同源音量不同哎。试了个动漫，30左右音量正常，试了个花木兰，音量要调到60左右才能有刚才这个30的感觉~
