### ISSUE TITLE
蓝凑云很久没更新了，github无法下载，能否同步更新一下？另外是否可以提供deb版本？

### ISSUE THREAD

**Issue by m2cc** [Hunlongyu/ZY-Player#268]

**Comment by Hunlongyu** [comment]
蓝奏云已更新, 话说 snap 格式的安装包, 可以安装成功么?

**Comment by Darling-Lee** [comment]
反正我是没有成功安装过，都是用Appimage解压手动安装的。其实我建议写一个sh或者打包一个run这样能适用于各个发行版会更加方便

**Comment by m2cc** [comment]
> 蓝奏云已更新, 话说 snap 格式的安装包, 可以安装成功么?

不能安装

**Comment by fgggid** [comment]
一直用的snap
`snap install --dangerous zy_2.5.2-1_amd64.snap`
如果snap没登陆，就加sudo

**Comment by m2cc** [comment]
> ubuntu 20.04.1，一直用的snap
> `snap install --dangerous zy_2.5.2-1_amd64.snap`
> 如果snap没登陆，就加sudo

我是deepin linux，debian系，没有这个命令

**Comment by fgggid** [comment]
deepin没用过，你试试apt install snapd呢？
