### ISSUE TITLE
有些苹果10的api，hplayer可以用，zy_player用不了，求解

### ISSUE THREAD

**Issue by 1083487093** [Hunlongyu/ZY-Player#269]
比如这个：
苹果10如何配置采集
本站可用api信息如下
乐播视频资源 https://lbapi9.com/api.php/provide/vod/at/xml/
备用乐播视频资源 http://lbapiby.com/api.php/provide/vod/at/xml/

**Comment by cuiocean** [comment]
目前只支持seacmsapi.php 或api.php 结尾的api接口
