### ISSUE TITLE
一点小建议希望采纳

### ISSUE THREAD

**Issue by cwwask** [Hunlongyu/ZY-Player#27]
这个软件真是好，源多不说，而且还简洁，牛逼~
当然，如果能：
1.软件可以自定义添加源，
2.做一下安卓手机或者电视盒子版本的。
以上建议希望作者考虑一下，谢谢！

**Comment by Hunlongyu** [comment]
😂谢谢夸赞~
1. 视频源需要手动敲代码,进行数据解析, 不同的源处理的方式不一样. 所以并不能自定义源.
2. 很多人都提到制作安卓版, 我这边有计划, 但是短期内做不来哦. 首先目前我掌握的技术并不包含手机端软件制作.我需要去学习.
3. 目前的视频其实画质都不高, 如果电视机的话,一放大更不能看了, 当然最重要的是, 我还没有掌握制作技术.

总结, 视频源,我会慢慢增加,.移动端的我可能会制作, 而且短期内也完不成.
