### ISSUE TITLE
建议可以用鼠标长按播放器位置拖动整个窗口及调整窗口大小的问题

### ISSUE THREAD

**Issue by Samdogcom** [Hunlongyu/ZY-Player#273]
现在在播放器位置长按放手就变成暂停播放了,有时不想全屏看,就会有经常要移动窗口的情况
现在只能按住左边或者上边部分地方才可拖动,比较不方便,特别是在样式全屏的时候

另外,无法在左边或者上边位置调整窗口的大小,但左边又不是完全不能调,有按键的那片地方却可以调
这样导致左下和左上角都无法调整窗口大小,当ZY的窗口靠屏幕右下角摆放的时候,想调整大小就非常的麻烦
希望能够改进一下,谢谢

**Comment by Hunlongyu** [comment]
如果经常使用 样式全屏的话, 建议试一试 MINI 精简模式呢.
