### ISSUE TITLE
小小的提议: iptv内的频道可以分类下，比如国内，国外，少儿等

### ISSUE THREAD

**Issue by king4107** [Hunlongyu/ZY-Player#275]
1、可否再播放iptv的时候在播放器左上角显示下播放的频道名称，比如再看cctv1的时候左上角显示cctv1
2、iptv内的频道可以分类下，比如国内，国外，少儿等

**Comment by cuiocean** [comment]
1. 已改进.请等待下一个版本.
2. 会在后续的版本逐渐更新.
