### ISSUE TITLE
投屏功能

### ISSUE THREAD

**Issue by WW872577514** [Hunlongyu/ZY-Player#276]
希望作者添加投屏功能

**Comment by cuiocean** [comment]
投屏的功能目前不会做进去,比较难.在播放界面右上角,有个按钮可以在第三方播放器打开视频.如果你没有设置第三方播放器的话,它会在网页播放器中打开. 那么这时,如果你有chrome cast的话,那么你就可以网页投屏了. 希望有所帮助.
![image](https://user-images.githubusercontent.com/5760235/95908876-ee103c00-0d9d-11eb-82bf-236c880b526d.png)
