### ISSUE TITLE
Question：请问是否方便对触屏设备进行一些适配？

### ISSUE THREAD

**Issue by zxkmm** [Hunlongyu/ZY-Player#278]
目前触屏设备的使用问题在于：

1.   自带播放器的倍速按钮无法用触屏进行操作
2.   正常播放时，呼出操作栏的操作对触屏设备不友好，因为会暂停视频
3.   待补充

非常感谢作者的项目，看视频方便了很多，祝作者工作顺利，阖家辛福!

**Comment by cuiocean** [comment]
查看了一下西瓜播放器的文档，发现
"默认video触发touchend事件后视频切换播放/暂停状态，通过closeVideoTouch关闭".
已关闭。请期待下一版本。
