### ISSUE TITLE
插耳机没有声音

### ISSUE THREAD

**Issue by Linger002** [Hunlongyu/ZY-Player#28]
版本0.9.31：笔记本win7，插耳机依旧外放，耳机没有声音，也无法使用SoundBooster来扩大声音，其他软件正常

**Comment by Hunlongyu** [comment]
1. 首先尝试重启电脑，重启软件，期间耳机一直插着不要拔。
2. 一般情况下声音问题都是电脑问题。软件很多人都在用，已经算是很稳定了。
3. 如果重启大法，也不行， 尝试重装软件。
