### ISSUE TITLE
作者您好，有个小建议

### ISSUE THREAD

**Issue by yamazaki1412** [Hunlongyu/ZY-Player#29]
一直在用您发布的各个版本。建议正式版恢复分享时显示片源M3U8地址。您后期版本只有二维码分享了，还要识别成地址，不是很方便。谢谢。

**Comment by Hunlongyu** [comment]
1. 你获取播放地址主要用来干嘛?
2. 现在点击分享, 会生成一张包含播放地址的电影海报图片. 可以直接粘贴到微信或者其他地方.并不需要手机扫描后, 再次转发分享.

**Comment by yamazaki1412** [comment]
作者您好。很高兴收到您的邮件。感觉您这个软件超级爽，真的很不错了，界面也很好看，使用起来也很方便。
现在分享是一张包括二维码的图片。倒是可以识别成地址，就是不如以前方便了。有了M3U8地址可以下载视频啊。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 中午11:33
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"张猛"<10274215@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] 作者您好，有个小建议 (#29)





  
你获取播放地址主要用来干嘛?
 
现在点击分享, 会生成一张包含播放地址的电影海报图片. 可以直接粘贴到微信或者其他地方.并不需要手机扫描后, 再次转发分享.

**Comment by Hunlongyu** [comment]
1. 如果想下载视频, 最大资源网和OK资源网 都提供下载链接.
2. m3u8格式的视频下载麻烦, 画质也并不会有提升, 一般人也不知道怎么下载.
3. m3u8 合并后的视频格式, 默认也是 mp4 的吧, 即使其他格式, 画质也一样的吧.
4. 主要是觉得这个需求有些困惑, 不过我会记录下来, 近期会优化一下.

**Comment by yamazaki1412** [comment]
谢谢。辛苦作者了。支持您！

**Comment by xu93nuo1987** [comment]
建议全屏添加下一集按钮，小窗口全屏也添加下一集按钮!

**Comment by Hunlongyu** [comment]
@yamazaki1412 
1. 我现在在准备相关事宜, 但是安卓版短期内制作不出来.

**Comment by yamazaki1412** [comment]
真不错。预祝顺利！

**Comment by p6858446** [comment]
全屏模式下建议增加下一集按钮或快捷键，这样对追剧党会比较友好，不用浪费时间在片尾曲上，现在需要切回窗口化再点下一集略麻烦。。。

**Comment by Hunlongyu** [comment]
@xu93nuo1987 @p6858446 
全屏状态下, 目前是无法做到显示下一集按钮的, 不过可以尝试添加快捷键.

需求已经收录, 请耐心等待近期更新.

**Comment by 20200519** [comment]
1主界面不能调整窗口大小，默认太小了，想弄大点  
2样式全屏下播放不能调整大小    主要是不想全屏，全屏不能做其他事情   0.9.1那个·版本很好用，样式全屏还能调整大小，可以做其他事情，还不耽误看视频  
3双击窗口最大化视频画面还是原来的大小，但软件窗体已经最大化了，最好视频画面跟着变大
4精简模式播放不能退回窗口模式播放，一点退出就回主界面了  ；这个功能其实跟样式全屏可以做到一起，样式全屏可以退回窗口播放，但视频继续播放

**Comment by Hunlongyu** [comment]
@xu93nuo1987 @yamazaki1412 @p6858446  @20200519 
## 更新日志
1. 新增全局快捷键, control + ➡ 下一集 . control + ⬅ 上一集 . control + ⬆ 增加不透明度. control + ⬇ 减少不透明度
2. 新增下载入口, 在浏览列表和收藏列表新增下载按钮. 
3. 新增下载格式, m3u8 , 之前只支持 mp4
4. 主界面现在可以调整大小. 并且优化部分样式.
