### ISSUE TITLE
安装已终止：安装程序并未成功地运行完成。

### ISSUE THREAD

**Issue by xjzh123** [Hunlongyu/ZY-Player#290]
win10，64位笔记本。不管怎么安装（管理员运行、改路径、换32位程序、改成为所有人安装）都提示这个。不在路径下创建ZY Player文件夹，也不创建可执行程序，只创建了没有icon的桌面快捷方式。

**Comment by Hunlongyu** [comment]
1. 先卸载老版本的 zy (如果安装过)
2. 删除  `C:\Users\hunlo\AppData\Roaming\zy ` 整个 `zy` 目录, 每个人的路径不一样, 自己找一找, 很容易找到
3. 最好重启一下电脑
4. 下载安装最新版本 zy, 目前最新版: 2.5.2-1. 全程默认就好.
