### ISSUE TITLE
最大化的时候关闭则下次启动后窗口会自动变大

### ISSUE THREAD

**Issue by phicommvip** [Hunlongyu/ZY-Player#293]
最大化-关闭ZY-重新启动ZY-这个时候ZY的窗口会变大到和最大化差不多的的大小，点最大化和还原窗口尺寸基本没有变化，就是没办法缩小，现在的版本是2.5.2.1这个问题好像是2.5.2开始出现的（大概吧）

**Comment by cuiocean** [comment]
这是那个版本的新的特性,重新打开会恢复到上次关闭时候的大小.

**Comment by cuiocean** [comment]
但貌似是,如果最大化后关闭,没有记录最大化的状态而是恢复到最大化的大小. 我们再看看用户反应, 我个人是觉得每次打开默认大小就挺好.

**Comment by phicommvip** [comment]
> 但貌似是，如果最大化后关闭，没有记录最大化的状态又恢复到最大化的大小。我们再看看用户反应，我个人是觉得每次打开大小大小就挺好。

嗯我也感觉默认大小就挺好

**Comment by cuiocean** [comment]
该特性也删除.现在打开后还是默认大小了.请期待下一版本.
