### ISSUE TITLE
其他皮肤下播放记录的光束能不能上移一点

### ISSUE THREAD

**Issue by phicommvip** [Hunlongyu/ZY-Player#294]
黑色皮肤下在播放记录里，鼠标移动到第一条记录但是亮起的光束太靠下了，会有一种错觉以为鼠标没放对，只有白色皮肤没有影响

另外播放记录界面的播放选项距离剧名太远了容易点错（原谅我近视眼）建议能不能把播放这个选项放在剧名的前面或者往前调一下
![QQ截图20201017181321](https://user-images.githubusercontent.com/71109116/96334580-70ea0d00-10a4-11eb-80ea-14ce7959473c.png)

**Comment by cuiocean** [comment]
关于第一条,下一个版本已经开始采用新的样式,不会有这个高亮光了. 会改变一下背景颜色来显示被选中的行. 如下:
![image](https://user-images.githubusercontent.com/5760235/96334818-ceb23100-1073-11eb-9a36-2ff0045beff8.png)

关于第二条, 现在是点击任何地方会进入详情页, 可以把播放和进入详情页调换一下. 就是加入"详情"按钮,取代播放. 然后单击任何地方就是播放.

**Comment by cuiocean** [comment]
关于第二条, 现在鼠标选中的行背景颜色会变化,很容易看清当前行的. 所以不需要更改播放按钮.
