### ISSUE TITLE
建议：增加个一键换源的功能

### ISSUE THREAD

**Issue by phicommvip** [Hunlongyu/ZY-Player#295]
建议在播放界面加个一键换源的功能，换源后自动定位到当前播放的位置，比如现在正在看寄生虫用的178资源网，这个时候突然卡了或者对清晰度不满意就可以一键切换到其他源，这样就不用重新搜索不用重新定位了，要不然重新搜索再定位到之前看到的位置一通操作下来很影响观看体验和心情的，

另外这个功能也可以适用于直播，比如CCTV1有好几个源就可以把这些源整合到一起，这样频道列表就不用显示那么多重复的频道了，播放的时候一个换台一个换源互不干扰

ZY基本上已经很接近于完美了我说的这些加不加其实没啥影响，只是我自己感觉还挺实用的希望大佬有时间了可以看一下有没有加入的必要

**Comment by buvta** [comment]
不同源之间资源可能也是不同的，并不是切换到相同进度就能继续，既然是直播就是换台啊

**Comment by phicommvip** [comment]
> 不同源之间资源可能也是不同的，并非切换到相同进度可以继续

换源的时候对标题进行一些筛选只切换标题一致的这样大部分源的内容应该是一致的就算时间长度不一样也不会差太多，而且就算用户自己手动重新搜索换别的源也有几率换到不一致的，如果换到不一致的资源只需要再换一次就好了，手动换源也是这样的吧，一键换源还更快更方便，就是这个算法筛选可能要耗费大量的时间吧，如果真的不容易做就算了反正现在已经很不错了

**Comment by Hunlongyu** [comment]
手动换源功能已实现, 一键换源的功能,并不实用.暂未添加.
