### ISSUE TITLE
视频源搜索问题和左右键前进后退的问题

### ISSUE THREAD

**Issue by Jacobax** [Hunlongyu/ZY-Player#297]
1.勾选了搜索所有，打开软件所搜，结果只有当前源的资源，要取消勾选再重新勾选所搜所有资源才行
2.快捷键是开启的，但是要关闭再重新开启，前进后退才生效，而上下调音量是没问题的

**Comment by phicommvip** [comment]
1：你用的是2.5.2吧？升级到2.5.2.1就好了这个问题我反馈过了

**Comment by Jacobax** [comment]
> 1：你用的是2.5.2吧？升级到2.5.2.1就好了这个问题我反馈过了

好的谢谢
