### ISSUE TITLE
能提供原始网页的链接吗？

### ISSUE THREAD

**Issue by freeleefly** [Hunlongyu/ZY-Player#3]
感谢作者。
建议1，搜索，能直接若干个网站直接一起搜，后面标注是来自于哪个网站。
建议2，倍速能自己调的话就更好了，好像[Video Speed Controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?hl=en)

**Comment by Hunlongyu** [comment]
1. 原始网页的链接，可以直接百度到，毕竟名字都写出来了。
2. 也不是没有考虑一起搜，主要是资源都重复，默认的第一资源是最多的。
3. 倍速由于插件问题，目前无法简单实现调速。

**Comment by freeleefly** [comment]
1. 原始网页的链接 这个是小问题啦，看作者你了。不过，不管是播放页面，还是详情页面，我发现，所有的文字都是不可选中的，更不要提拷贝复制了。就有一种鼠标木木的感觉。不过这个毕竟不是网页。但是看到文字，然后不能选中，还不能F12进去看，真的很挠头😂。
2. 倍速需要插件吗？我记得我看html5的时候，好像video可以有速度属性的，以为直接改就好了。我想少了。

作者加油！

**Comment by Hunlongyu** [comment]
已更新，不需要下载，会后台自动下载，下次启动更新
1. 详情页可以复制了
2. 是播放视频的插件，不支持自定义倍速。

freeleefly <notifications@github.com> 于2020年2月13日周四 下午8:00写道：

**Comment by freeleefly** [comment]
嗯，收到更新了，很好。
通知里有版本号，一闪而过，软件里面没有一个版本号，当时嘀咕没有一个保持更新的选项😂

感恩。
