### ISSUE TITLE
有个小想法不知可行否

### ISSUE THREAD

**Issue by king4107** [Hunlongyu/ZY-Player#302]
1、希望有个账户功能，这样PC版和APP版用同一个账户就好同步收藏夹了。
2、版本v2.5.2不能搜索所有资源，必须重新打下勾才可以。

**Comment by Hunlongyu** [comment]
1. 目前软件的数据库, 都是本地的离线数据库. 网络同步的话,就需要服务器, 服务器就需要钱, 而软件是免费使用的, 并没有额外费用来支付服务器的租赁费用.

2. 目前最新版是 2.5.2-1 , 最新版没有问题哦~
