### ISSUE TITLE
询问一下分类里面的排序

### ISSUE THREAD

**Issue by lmvcl** [Hunlongyu/ZY-Player#308]
最新里的排序是按更新时间排的，但具体的分类更新时间是乱的。
![2020-10-23 2-30-58](https://user-images.githubusercontent.com/47291512/96916041-95494d80-14d9-11eb-95b1-44282c8060c3.png)

**Comment by cuiocean** [comment]
这就是资源站返回来的列表顺序，我们没有重新排序。
