### ISSUE TITLE
电视直播没有下拉条

### ISSUE THREAD

**Issue by king4107** [Hunlongyu/ZY-Player#309]
电视直播没有下拉条，用滚轮下拉太慢了
希望把电视直播内的频道，分组，操作做成固定顶层

**Comment by cuiocean** [comment]
有下拉条啊，只是2.5.4版本里有。
![image](https://user-images.githubusercontent.com/5760235/97237134-e3ff2c00-17e6-11eb-809c-a2623b55cbd5.png)
