### ISSUE TITLE
建议可以在分享按钮隔壁增加投屏功能。

### ISSUE THREAD

**Issue by linsongze** [Hunlongyu/ZY-Player#31]

**Comment by Hunlongyu** [comment]
软件用前端 JS 语言写的, 目前据我了解投屏功能还实现不了. 当然可能是我技术不到家, 不过确实没有办法解决.

**Comment by linsongze** [comment]
https://github.com/gyzerok/nodecast-js  我昨晚自己试了下，在播放视频的时候，直接调用这个库的接口，是可以投屏将m3u8投屏到电视的，，但是由于不会前端，，，我弄到有点头皮发麻。。。
`      tools.detail_get(this.video.site, this.video.detail).then(res => {
        this.name = this.video.name
        this.right.listData = res.m3u8_urls
        console.log(this.right.listData)
        if (res.m3u8_urls.length > 1) {
          const m3 = res.m3u8_urls
          const arr = []
          for (const i of m3) {
            arr.push(i.split('$')[1])
          }
          this.xg.src = arr[this.video.index]
          aaa = arr[this.video.index]
          this.showNext = true
        } else {
          const link = res.m3u8_urls[this.video.index]
          const src = link.split('$')[1]
          this.xg.src = src
          aaa = src
          this.showNext = false
        }
        console.log(aaa)

        const timestamp = 60 // in seconds
        const nodeCast = new NodeCast()

        nodeCast.onDevice(device => {
          device.onError(err => {
            console.log(err)
          })
          console.log(nodeCast.getList())// list of currently discovered devices

          device.play(aaa, timestamp)
        })
        nodeCast.start()`

**Comment by Hunlongyu** [comment]
可以啊, 大兄弟~ 我晚点尝试弄一下~

**Comment by Hunlongyu** [comment]
@linsongze 我用我的小米电视试了一下，并没有成功。 
没有搜索到播放设备

我用手机投屏可以找到小米电视，并成功播放。

可以加微信讨论一下嘛？
微信号：Hunlongyu
备注：GitHub
