### ISSUE TITLE
2.5.3 停止播放按钮异常

### ISSUE THREAD

**Issue by Cities2000** [Hunlongyu/ZY-Player#317]
播放视频后，点击停止播放按钮后，画面黑屏，但是声音继续存在，会自动回到视频开始位置播放，无法关闭，只能关闭软件后才行。

![Win10 2004](https://user-images.githubusercontent.com/25782778/97110676-8353ee80-1715-11eb-9f94-c1452fbafc8e.png)

**Comment by Hunlongyu** [comment]
2.5.4 版本进行了修复.
