### ISSUE TITLE
建议 

### ISSUE THREAD

**Issue by kosserYN** [Hunlongyu/ZY-Player#32]
以海报的方式显示影片列表 
进入精简模式后无法退回原本的模式
播放视频后无法关闭视频 只能替换播放

**Comment by Hunlongyu** [comment]
1. 海报功能可以实现, 不过不建议这么操作, 因为会瞬间请求50多次, 很容易被网站屏蔽. 而且加载资源很多, 会很慢. 所以暂时不提供海报功能.
2. 精简模式 确实是设计缺陷. 不过目前没有好的办法.
3. 视频只有暂停, 没有停止. 如果不想播放的话, 暂停即可. 不会占用带宽.
