### ISSUE TITLE
建议编辑源能加个测试源能否使用的功能

### ISSUE THREAD

**Issue by xu93nuo1987** [Hunlongyu/ZY-Player#320]
1.建议编辑源能加个测试源能否使用的功能。
2.播放直播时禁用速度倍数。

**Comment by arthur1976** [comment]
千万别加这个功能  这是播放器又不是别的

**Comment by Hunlongyu** [comment]
第一个可以实现的, 放到下个版本的开发计划里吧.
至于第二个, 看直播视频时候, 不点击倍速...就好了呀😂

**Comment by Hunlongyu** [comment]
检测源的功能已经添加上, 下个版本放出, 敬请期待哈~
