### ISSUE TITLE
添加 ARM 版本

### ISSUE THREAD

**Issue by hmsjy2017** [Hunlongyu/ZY-Player#323]
我想在树莓派上使用 `ZY-Player`，然而并没有提供 `armhf` 版本，也没有找到编译说明。

**Comment by Hunlongyu** [comment]
我查阅了相关资料, 说是
树莓派可以安装 AppImage 格式的安装包. 如果是 x64 位的话, GitHub relases 里有 AppImage 安装包.
如果 x86 的话, 可能就需要你自己打包了哦~

**Comment by hmsjy2017** [comment]
如何自己打包 armhf 版本？没有找到教程
