### ISSUE TITLE
最近播放视频的时候总是音画不同步，以前播放没问题，新版本会有这种情况

### ISSUE THREAD

**Issue by yjys668** [Hunlongyu/ZY-Player#324]
RT

**Comment by Hunlongyu** [comment]
有可能是这个视频有问题, 换个视频呢?

**Comment by yjys668** [comment]
换个视频，换个源还是这样，卡顿的时候连页面滑动都明显感觉到卡。之前没遇到过这种情况，前天发现的，不过现在貌似没问题了。

**Comment by Hunlongyu** [comment]
可能是你自己的网络波动.比如给系统后台更新, 导致网络堵塞.

**Comment by yjys668** [comment]
又出现那种情况了 感觉不像是网络问题 倒像是硬件和软件之间的问题 我用360看视频的时候有时也会这样 但换其他浏览器就好很多
