### ISSUE TITLE
换源功能很不错希望可以继续优化

### ISSUE THREAD

**Issue by phicommvip** [Hunlongyu/ZY-Player#325]
谢谢大佬换源功能真的太实用了，希望可以继续优化，现在是换源后会从头开始播放，有没有办法换源后自动定位到换源前的位置继续播放呢-_-

**Comment by lukemin** [comment]
这个应该不难实现，但就是实现会有误差，因为各个不同的源的电影的时长可能不同。

**Comment by phicommvip** [comment]
> 这个应该不难实现，但就是实现会有误差，因为各个不同的源的电影的时长可能不同。

有误差也没关系自己稍微拉一下就好了，总比从头开始要好，特别是电视剧还要记住看到多少集了，直接跳到当前集数多方便

**Comment by cuiocean** [comment]
已经解决，现在可以在新源中打开当前剧集，定位到当前时间。请期待下一版本。
