### ISSUE TITLE
能不能把自己添加某些源隐藏，需要密码才能进入？

### ISSUE THREAD

**Issue by lukemin** [Hunlongyu/ZY-Player#326]
自己添加的源有些18+的，但是电脑家人有时候也用，能不能把这些源这些源隐藏，需要密码再进入？

**Comment by phicommvip** [comment]
好建议支持+1  补充一下，在同时勾选搜索所有资源 和加密的情况下搜索的时候不搜索加密的源

**Comment by cuiocean** [comment]
2.6.0版本支持密码保护，有密码才能编辑源。

**Comment by lukemin** [comment]
> 2.6.0版本支持密码保护，有密码才能编辑源。
还没理解我们的意思，我们需要进入的时候选择源的时候就要输入密码，或者输入特定密码解锁隐藏频道。

**Comment by cuiocean** [comment]
你可以进入编辑源，把一些特定的源关闭。关闭的源不会出现在影视页面。你加上密码，只有输入密码才能打开或关闭源。

**Comment by lukemin** [comment]
源多的话，一个一个点有点麻烦啊。

**Comment by cuiocean** [comment]
源支持分组 也支持批操作的
