### ISSUE TITLE
能不能增加跳过片头片尾功能

### ISSUE THREAD

**Issue by 35655a** [Hunlongyu/ZY-Player#328]

**Comment by cuiocean** [comment]
每个剧的片头片尾长度都比一样的。你看一个剧,你可以设置第三方播放器,比如PotPlayer,然后播放第一集,点击第三方播放器打开,会导出该剧所有剧集到m3u文件,并用PotPlayer打开. 在PotPlayer里面,就可以设置跳过片头片尾了. 
![image](https://user-images.githubusercontent.com/5760235/97800536-45cff380-1c36-11eb-9d62-386be85ccaad.png)
