### ISSUE TITLE
这个软件开发以来一直在用，谢谢开发者，辛苦了

### ISSUE THREAD

**Issue by wenrtxn** [Hunlongyu/ZY-Player#33]
这个软件使用以来，不知道那个记录播放历史是不是只能记录播放的视频，而不是记录播放到某集的记录，每次再次看的时候都是重新从第一集开始播放，不管是普通模式还是精简模式，

**Comment by Hunlongyu** [comment]
在设置里 有个重置软件按钮，尝试一下。

**Comment by Hunlongyu** [comment]
@wenrtxn 
可以了么?

**Comment by wenrtxn** [comment]
@Hunlongyu 最近几天有事没看到，但是今天测试了最新的10的版本，在精简模式下播放ok网站的视频，比如自动播放了1-3集体，这个时候想提前看第4集，点下一级左上角那个向右的箭头，会自动跳到第4集，但是问题出问题了，左上角显示的是第4集，内容却是刚刚看过的第3集，这个问题开发以来一直存在

**Comment by wenrtxn** [comment]
@Hunlongyu 最上面那个问题，一直存在，每次出新版本都是重新安装的，原来的版本完全删除zy那个记录文件夹也删除了，x64win7专业版本，软件安装在D盘不是系统盘，喜欢用精简模式看视频，但是退出精简模式后，重新点收藏的播放，居然还是播放第一集，是不是收藏里面没有保存播放记录

**Comment by Hunlongyu** [comment]
@wenrtxn 
新版本发布, 修复了精简模式下 历史记录混乱的问题. 
确实少了一句代码. 谢谢测试反馈哈
😘

**Comment by Hunlongyu** [comment]
@wenrtxn 
之前修复的 bug 不是你描述的 bug.  😂
不过新版本已发布, 已解决.
话说 历史记录这里 确实问题很多.😅
