### ISSUE TITLE
希望添加下载缓存功能，能提前缓冲下载好观看的电视剧，

### ISSUE THREAD

**Issue by hualuoshuijia** [Hunlongyu/ZY-Player#331]
有很多资源站点缓冲很慢，看视频的时候每隔几秒就转圈圈，虽然可以换源，但不免都是站源不给力者，有提前下载视频功能，避免看视频时性子急躁，
比如《大秦帝国之纵横》未删减版51集，只有两个站源有，却都转圈圈，

**Comment by phicommvip** [comment]
你这个建议让我想起了多年前的乐鱼播放器，乐鱼就是一直缓存甚至看电视剧的时候连下一集都给你缓存一部分，这样看下一集的时候不用等待缓存直接就能播放，但是这样会给网站造成一定的负担所以现在大多数网站都是看一段缓存一段，如果站源不支持全集缓存我想ZY应该没办法，这都是我自己猜的哈具体还是要等大佬来评估

**Comment by hualuoshuijia** [comment]
> 你这个建议让我想起了多年前的乐鱼播放器，乐鱼就是一直缓存甚至看电视剧的时候连下一集都给你缓存一部分，这样看下一集的时候不用等待缓存直接就能播放，但是这样会给网站造成一定的负担所以现在大多数网站都是看一段缓存一段，如果站源不支持全集缓存我想ZY应该没办法，这都是我自己猜的哈具体还是要等大佬来评估

是啊  等大佬评估，自己也不懂 只是希望软件越来越好用，说一下自己使用软件的感受，

**Comment by hualuoshuijia** [comment]
> 你这个建议让我想起了多年前的乐鱼播放器，乐鱼就是一直缓存甚至看电视剧的时候连下一集都给你缓存一部分，这样看下一集的时候不用等待缓存直接就能播放，但是这样会给网站造成一定的负担所以现在大多数网站都是看一段缓存一段，如果站源不支持全集缓存我想ZY应该没办法，这都是我自己猜的哈具体还是要等大佬来评估

对我自己来说只要站源能再快100k的速度就好了，自己看视频不要求画质，剧情比画质重要的多，奈何很多站点卡的直转圈圈

**Comment by mobaibai** [comment]
这个功能的确很实用

**Comment by cuiocean** [comment]
设置默认默认预加载300秒. 请更新到2.6.7版本.
