### ISSUE TITLE
建议增加追番追剧功能

### ISSUE THREAD

**Issue by phicommvip** [Hunlongyu/ZY-Player#333]
建议增加追番追剧功能
看动漫和没有完结的电视剧最痛苦的就是记不住什么时候更新，特别是同时追多部动漫有的周一更新、有的周四更新，每次都要一部一部挨个点开看太麻烦了，能不能让用户把想追的剧加入到追剧列表，然后每次打开追剧列表自动检测该列表内的剧是否有更新，如果有更新的则用数字或图标提示，这样以后追番追剧就简单多了-_-

**Comment by Hunlongyu** [comment]
收藏夹有个同步功能。就是检测是否有更新， 追剧的功能。
