### ISSUE TITLE
换源后无法定位到当前的时间进度

### ISSUE THREAD

**Issue by phicommvip** [Hunlongyu/ZY-Player#334]
换源后可以定位到当前剧集了太好了，但是时间进度还是无法定位，如果时间进度也可以自动定位就更好了

**Comment by cuiocean** [comment]
时间进度有个采样频率 你多播放一会儿再换源试试看

**Comment by phicommvip** [comment]
> 时间进度有个采样频率 你多播放一会儿再换源试试看

一集电视剧播到三分之二的时候卡了，换源后还是从头开始，电影看了20分钟了换源后也是从头开始，这个采样频率建议微调一下

**Comment by cuiocean** [comment]
采样的时候没有更新一个变量, 所以换源时时间进度没有被设置好. 已经解决,请期待下一版本.
