### ISSUE TITLE
UOS V20 个人版无法启动

### ISSUE THREAD

**Issue by fatefl** [Hunlongyu/ZY-Player#34]

**Comment by Hunlongyu** [comment]
额~~
软件是在Win平台开发的, 目前只能确保 Win 能正常播放. 不过我有时间, 安装一个 UOS 试一试.

**Comment by uiYzzi** [comment]
运行的时候加上 --no-sandbox参数就好了

**Comment by Hunlongyu** [comment]
@uiYzzi 
感谢大佬技术支持~

**Comment by fatefl** [comment]
> 运行的时候加上 --no-sandbox参数就好了
@uiYzzi
感谢大佬~ ，这样确实可以运行，只是对于普通用户使用有些不方便

**Comment by Hunlongyu** [comment]
@uiYzzi 
可以右键图标， 在路径里填写 参数么？ 类似 Windows ?

**Comment by Hunlongyu** [comment]
@fatefl  @uiYzzi 
我这边新增了 --no-sandbox 参数， 下个版本还请帮忙测试一下。😂

**Comment by fatefl** [comment]
可以的

**Comment by Hunlongyu** [comment]
@fatefl 
最新版 v1.0.7 加上了  --no-sandbox 参数. 你可以正常运行了么?

**Comment by fatefl** [comment]
试过还是不行， 提示这个

**Comment by Hunlongyu** [comment]
@fatefl 
脑壳痛, 我只是一个前端开发 ...
话说 你安装的是什么包呀? snap 还是 AppImage ?

**Comment by fatefl** [comment]
@Hunlongyu  AppImage包

**Comment by Hunlongyu** [comment]
要不试一试 snap 包?
链接: https://github.com/Hunlongyu/ZY-Player/releases/download/v1.0.7/zy_1.0.7_amd64.snap

**Comment by Hunlongyu** [comment]
算了, 我回去安装一个 UOS 吧, 不麻烦你们了

**Comment by Hunlongyu** [comment]
@fatefl 
你的 UOS V20 怎么激活的呀？
我从官网下载的  操作系统x86_64 个人体验版
需要激活
可以加微信交流一下么？
微信号：hunlongyu

**Comment by uiYzzi** [comment]
> @fatefl
> 你的 UOS V20 怎么激活的呀？
> 我从官网下载的 操作系统x86_64 个人体验版
> 需要激活
> 可以加微信交流一下么？
> 微信号：hunlongyu

--no-sandbox要在.desktop文件里面加，建议打包成deb，这样会方便一点

**Comment by uiYzzi** [comment]
> @Hunlongyu AppImage包

建议使用[AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher/releases)安装appimage包，然后手动在~/.local/share/applications/ 里的.desktop文件里添加--no-sandbox
这样只需要添加一次，以后可以直接点击图标打开

**Comment by uiYzzi** [comment]
> @Hunlongyu AppImage包

![类似这样](https://s1.ax1x.com/2020/05/31/tltYqA.png)

**Comment by Hunlongyu** [comment]
最新正式版: v2.x 已发布, 欢迎体验.
