### ISSUE TITLE
关于“最小化窗口后暂停播放，恢复窗口后继续播放”功能的 问题和建议反馈

### ISSUE THREAD

**Issue by loverubywithout** [Hunlongyu/ZY-Player#349]
版本：2.6.4
系统：win10
安装方式：为所有用户安装
问题描述：问题在2.6.3时就有了，当最小化后，的确暂停播放了，但是恢复窗口后并未继续播放，需要自己手动开始播放，我用管理员权限启用也没用； 然后这个功能，希望能作为一个开关，是否开启此功能，谢谢，因为比如我，希望最小化还能继续播放。

**Comment by cuiocean** [comment]
至今为止最标准的问题报告👍👍

**Comment by Hunlongyu** [comment]
这个其实不是问题， 而是一个功能，不过没有考虑周全，可以改为可设置项。

**Comment by buvta** [comment]
想要继续播放的话，不最小化直接切换窗口不就行了？

**Comment by cuiocean** [comment]
已解决恢复窗口视频不继续播放的问题.
