### ISSUE TITLE
第三方播放器希望增加多个播放接口

### ISSUE THREAD

**Issue by FreeGAV** [Hunlongyu/ZY-Player#351]
增加多个播放接口
![QQ截图20201113200047](https://user-images.githubusercontent.com/29408312/99070675-a7f00780-25eb-11eb-984c-79173c163aea.png)

播放界面 第三方播放器点击  非本地播放器  非仅有一个播放接口时弹出播放接口选择列表
![QQ截图20201113200033](https://user-images.githubusercontent.com/29408312/99070662-a292bd00-25eb-11eb-9f79-53b169b6138a.png)

**Comment by cuiocean** [comment]
为何有此需求呢?

**Comment by FreeGAV** [comment]
使用自己的解析接口加速M3U8源

**Comment by cuiocean** [comment]
但为什么要设置多个第三方播放器呢？

**Comment by buvta** [comment]
没必要吧，考虑到大多数用户的需求
