### ISSUE TITLE
电视直播视频源部分失效

### ISSUE THREAD

**Issue by 724007104** [Hunlongyu/ZY-Player#354]
**描述错误**
清楚简洁地说明错误是什么。

**重现**
重现行为的步骤

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by arthur1976** [comment]
是啊 100多个直播源都失效了。。。很多中央台也看不成了

**Comment by buvta** [comment]
直播源只能靠你们自己找了，即使同一直播源不同地区网络运营商使用的效果可能亦会有差异，开发已经很耗精力了我们无力再维护更新列表，抱歉！
