### ISSUE TITLE
直播源都很难打开啊 

### ISSUE THREAD

**Issue by arthur1976** [Hunlongyu/ZY-Player#355]
**描述错误**
清楚简洁地说明错误是什么。
打不开或很卡
**重现**
重现行为的步骤

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by buvta** [comment]
明明已经提示删除未回复问题了，而且这个问题也有人问过😓️请搜索
