### ISSUE TITLE
IPTV建议可以设置超过多长时间没有响应后自动换源

### ISSUE THREAD

**Issue by phicommvip** [Hunlongyu/ZY-Player#358]
天冷了看直播的时候不想一直伸出手换源,但是有时候一直卡着不动不得不换源,能不能加个设置,超过预设定的时间后还在卡着不动就自动换源,另外希望大佬多找一些三大运营商都不卡的直播源比如我现在用的这个http://39.134.65.162/PLTV/88888888/224/3221225686/index.m3u8经测试联通电信移动播放都不卡而且秒播,怎么来的是不是长久都不知道就是网上找来的,大佬有时间可以研究一下

**Comment by yoholo** [comment]
直播源可以是其他项目分享的，会自动更新，全国全网可看，不增加维护精力和成本。。。
你的直播源，我这就不能播放。
Tvlist-awesome-m3u-m3u8 就是选择之一
