### ISSUE TITLE
更新到最新版2.6.6后无法使用

### ISSUE THREAD

**Issue by goeway** [Hunlongyu/ZY-Player#359]
原本安装的2.4.x 一直都能正常使用
升级到2.6.6后就无法使用了
打开后首页一直在转圈圈

win10 1909 64位家庭版

**Comment by cuiocean** [comment]
你有没有试试重置一下？

**Comment by buvta** [comment]
请读下更新日志

**Comment by qq784793169** [comment]
2.66后我也不能用了

**Comment by goeway** [comment]
> 请读下更新日志

重置后正常了

**Comment by v21cesc** [comment]
设置页面下面 有个请作者吃辣条，然后再下面有个重置软件，点一下就能用了
