### ISSUE TITLE
关于添加源

### ISSUE THREAD

**Issue by lpdswing** [Hunlongyu/ZY-Player#360]
### 版本、安装方式、系统

1. 你在使用什么版本的
2.5.5
2. 你通过什么方式安装
dmg
3. 你所使用的操作系统
mac bigsur

### 描述问题：

关于视频源添加问题,我想问这个源接口是自己找的还是自己爬虫制作,我发现一个资源很不错的视频源想添加

**Comment by buvta** [comment]
请看“常见问题”
