### ISSUE TITLE
许多直播源都已失效！（未回答的问题请删除）

### ISSUE THREAD

**Issue by 252978085** [Hunlongyu/ZY-Player#365]
希望及时更新，另外直播源的类别请正确区分，比如香港的 就全部放在港澳台   现在香港的既存在于港澳台又有卫视！

**Comment by billylxy** [comment]
直播我就没能正常看过，一直黑屏，体验非常差，应该去掉直播。

**Comment by buvta** [comment]
佛系更新了下直播源，使用前最好检测下，执行后可以切换到其它页面，检测会在后台继续运行，频道不可看时试下“换源”

请等待新版发布
