### ISSUE TITLE
看30秒，等3分钟（未回答的问题请删除）

### ISSUE THREAD

**Issue by kenhooooo** [Hunlongyu/ZY-Player#366]
**描述错误**
看30秒，等3分钟，看个电影没有一句话是可以连续听完的

**重现**
重现行为的步骤

**预期行为**
像个正常的播放器

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：win10 64位
  -软件安装包及版本：2.66

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by kenhooooo** [comment]
进度条没有任何缓存可言

**Comment by buvta** [comment]
所有源都是这样？网络是否正常？有无使用全局代理？将软件重置下看看

**Comment by 724007104** [comment]
之前的版本没有这个问题，一样的源，现在播一秒卡3秒。太难了

**Comment by buvta** [comment]
最和代理有关，新版本调整了下，请等待新版本发布
