### ISSUE TITLE
建议加上变速快捷键

### ISSUE THREAD

**Issue by beyond7100** [Hunlongyu/ZY-Player#37]
看油管的时候变速快捷键感觉很好用，shift+.是加速，按一下变1.25倍速，再按就是1.5倍速等等，shift+,是减速，尤其看电视剧的时候感觉用的挺多的，希望加上这个快捷键

**Comment by Hunlongyu** [comment]
以加上， 不过快捷键是： shift + up or down

**Comment by beyond7100** [comment]
我刚才试了一下，快捷键是好使的，但是用快捷键变速的时候右下角的速度倍数不变，就是说，视频已经是2倍速播放了，但是右下角还是显示1x

**Comment by Hunlongyu** [comment]
嗯~ 这个我也发现了， 我已经提交给插件issues 了，等待他们答复或者修复。

**Comment by beyond7100** [comment]
好嘞，话说能不能把全屏也加上快捷键呢（我就不再开个issue了，since都是快捷键问题），设定个F或者之类的，看视频的时候还是习惯像看油管一样，基本所有的操作都想用键盘完成，会方便很多

**Comment by Hunlongyu** [comment]
下个版本吧， 还有很多人都不会fq。
