### ISSUE TITLE
Mac Big Sur 无法使用软件

### ISSUE THREAD

**Issue by isTrophy** [Hunlongyu/ZY-Player#370]
打开软件 完全没有内容显示，电影，影视推荐等页面打开空白
![image](https://user-images.githubusercontent.com/4415586/100628785-8faa1780-3363-11eb-8d7e-68051ff7103d.png)

**Comment by cuiocean** [comment]
重置一下

**Comment by isTrophy** [comment]
@cuiocean  如何重置？

**Comment by cuiocean** [comment]
![image](https://user-images.githubusercontent.com/5760235/100741805-611b5380-33da-11eb-8427-34667a7eb9fc.png)

**Comment by isTrophy** [comment]
@cuiocean it works, thanks!
