### ISSUE TITLE
请安装到一般显示已经停止安装   最新版本

### ISSUE THREAD

**Issue by hdward** [Hunlongyu/ZY-Player#371]
**描述错误**
清楚简洁地说明错误是什么。

**重现**
重现行为的步骤

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by cuiocean** [comment]
不明白你要报告的是什么问题,请表述的更明白一些.
