### ISSUE TITLE
2.68程序启动后就是一个白框,其他什么也没有

### ISSUE THREAD

**Issue by lczlcz** [Hunlongyu/ZY-Player#372]
程序启动后就个白色的框框, 里面什么也没有. 等了很久还是这个样子. 可以用At-F4关闭, 但是重新启动还是这样. 
把appdata\roaming\zy 目录删除后重新启动程序还是这个样子. 
Taskbar上有图标. 看process list里面有三个zyplayer.exe

**Comment by cuiocean** [comment]
在设置里 重置软件

**Comment by lczlcz** [comment]
这个程序根本进不去啊, 就是一个白框, 里面什么都没有. 鼠标点上去也没用. 哪里可以看到设置?

**Comment by lczlcz** [comment]
今天再run这个程序, 又好了.
