### ISSUE TITLE
怎么从2.6.6开始没有样式全屏了？

### ISSUE THREAD

**Issue by billylxy** [Hunlongyu/ZY-Player#375]
怎么从2.6.6开始没有样式全屏了？
已经习惯样式全屏，突然没有了，使用起来感觉不顺手哇~

**Comment by buvta** [comment]
和精简模式统合了，精简模式就是可以保存窗口状态的样式全屏

**Comment by billylxy** [comment]
不如以前好用，而且对触控屏不太友好

**Comment by billylxy** [comment]
拜托还是把样式全屏添加上吧，或者两种方式都存在，触控屏上用精简模式的话没办法在返回去了。

**Comment by buvta** [comment]
升级版本，新版本已添加
