### ISSUE TITLE
manjaro无法启动

### ISSUE THREAD

**Issue by qianyigengwu** [Hunlongyu/ZY-Player#38]
terminated by signal SIGSEGV (Address boundary error)

**Comment by Hunlongyu** [comment]
@qianyigengwu 
软件是在 Win 上开发的,  并不能保证 Linux 等其他平台系统能正常运行. 
不过我这边会安装 manjaro 进行测试的.
只是我这边经常加班, 时间上会延迟

**Comment by qianyigengwu** [comment]
非常抱歉，是我操作失误，manjaro上正常使用。
真的非常抱歉耽误您时间了。

**Comment by Hunlongyu** [comment]
😁 能用最好了, 刚准备下载个 manjaro ,晚上回去弄一下.😝
