### ISSUE TITLE
可以添加一个VIP解析的接口功能，和测速功能

### ISSUE THREAD

**Issue by 130252251** [Hunlongyu/ZY-Player#380]
VIP解析的接口网上有很多，集成进去做成一个功能，把各大网站连接放上去，使用这些接口一键解析，再添加个单个的测速功能，就会非常完美了。不知道这个想法行不行，辛苦了大佬！

![N8P~)BK6~ P~JNV338%6IW5](https://user-images.githubusercontent.com/75723161/101638748-6d05b600-3a69-11eb-9183-99712a9b07aa.png)
![IMG_8944](https://user-images.githubusercontent.com/75723161/101638813-84dd3a00-3a69-11eb-8b85-c9462bad8ca7.PNG)
![IMG_8943](https://user-images.githubusercontent.com/75723161/101638820-87d82a80-3a69-11eb-9b01-2834cb746740.PNG)

**Comment by buvta** [comment]
这会导致软件直接侵权

**Comment by 130252251** [comment]
> 这会导致软件直接侵权
那现在这些源里的电影等不也都是盗版的吗？都没有版权，就没问题？
网上这样的VIP解析接口网站，多得很，手机端也有也多VIP解析的软件。。
我们只是这些东西的搬运工，源里的盗版可以搬运，VIP解析接口也可以搬运吧

**Comment by buvta** [comment]
即使添加接口，软件内置播放器也不一定能播放，有需要还不如直接找相关脚本

**Comment by 130252251** [comment]
> 即使添加接口，软件内置播放器也不一定能播放，有需要还不如直接找相关脚本
恩，这个就是技术性问题了，只是提供一个这样便民的想法，能不能解决要看大佬的了，能够添加这样一个功能肯定是会大受欢迎的，播放的资源能够更广些，弄不了那也没办法了。。
播放VIP解析后的视频，咱也不懂，只能期待大佬了
