### ISSUE TITLE
win10安装已终止

### ISSUE THREAD

**Issue by xiaofengvsbaby** [Hunlongyu/ZY-Player#382]
安装程序并未成功地运行完成，用了管理员权限也不行

**Comment by hdward** [comment]
同问  是之前版本注册表没清理干净吗 试了很多次不行 安装不完显示已停止

**Comment by hdward** [comment]
> 安装程序并未成功地运行完成，用了管理员权限也不行

去控制面板找到卸载程序 然后找到zyplayer   卸载掉再安装就可以了
