### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by maicalwang** [Hunlongyu/ZY-Player#39]
提示由于找不到ffmpeg.dll,无法继续执行代码。

**Comment by Hunlongyu** [comment]
什么系统? Win ? Mac ? Linux ?
多少位的操作系统? x64 ? x86 ?
第一次安装, 还是覆盖安装,又或者是更新?
尝试安装 老一点的版本试试, 现在是 v1.0.10, 安装 老一点版本: v1.0.7 等.

**Comment by Hunlongyu** [comment]
@maicalwang 
问题解决了么?
