### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by FreeGAV** [Hunlongyu/ZY-Player#4]
1.增加自定义添加资源站

2.文件太大，国内无法下载   希望增加百度网盘或蓝奏网盘下载

**Comment by Hunlongyu** [comment]
1. 我搜索了20多个资源网站，一一进行对比，发现只有列出来的几个资源齐全，且格式一致。用户自定义的难度很大，所以暂不考虑这个。

2. 已添加蓝奏云网盘和诚通网盘。

**Comment by aishyh** [comment]
1.可以添加下载功能吗
2.可以自己选缓存地址吗

**Comment by nbtjw** [comment]
播放有声音没画面，什么情况？

**Comment by Hunlongyu** [comment]
> 1.可以添加下载功能吗
> 2.可以自己选缓存地址吗
> 3.可以选择安装地址吗

1. 暂不会提供下载功能，如果想下次看，可以收藏，如果想手机看，可以扫描二维码。最重要原因，视频格式是 m3u8，目前没有好的办法解决。
2. 默认情况下，cookie 和缓存都会储存在 userData 文件夹。 不建议修改缓存地址。
3. 可以选择安装地址，但是同样不建议修改安装地址。后面可以考虑出个便携版，自行放置文件夹。

**Comment by Hunlongyu** [comment]
> 播放有声音没画面，什么情况？

一般遇到这种问题，请尝试：
1. 重启软件
2. 切换视频源
3. 重启电脑
4. 重装软件
