### ISSUE TITLE
能提供一个关闭硬件加速的选项吗

### ISSUE THREAD

**Issue by marsvet** [Hunlongyu/ZY-Player#40]
作者你好，能提供一个关闭硬件加速的选项吗，因为显卡驱动对linux的支持一直不好，全屏+倍速看视频的时候每过几秒就会卡住，动动鼠标才能恢复，以前在chrome上看视频也有这样的问题，关闭chrome的硬件加速就解决了，我翻了一下electron的文档，electron应该默认启用了硬件加速，也提供了关闭硬件加速的api，希望作者能提供一个设置项，可以让用户手动关闭硬件加速，谢谢😁

**Comment by Hunlongyu** [comment]
新版本已发布. 我这边默认关闭了 Linux 硬件加速功能.
