### ISSUE TITLE
提建议

### ISSUE THREAD

**Issue by wenrtxn** [Hunlongyu/ZY-Player#42]
1、在关闭精简播放模式后，能不能自动退到普通播放模式，而不是完全关闭视频或者提供一个返回普通模式的操作。（目前没明显的从精简模式回到普通播放模式的操作，不知道是不是没细心看）
2、收藏里面能不能保存播放进度记录或下次点击收藏那里播放的是当前的播放进度。

**Comment by Hunlongyu** [comment]
@wenrtxn 
精简模式 与 普通窗口 是相互独立的. 只是可以互相唤醒.
这是设计之初的没有想到的缺陷.
未来有时间, 我会想办法优化的.

收藏夹最新版: v1.0.12 ,已修复.
