### ISSUE TITLE
建议增加一个资源网站

### ISSUE THREAD

**Issue by panh0316** [Hunlongyu/ZY-Player#43]
https://www.88ys.com/，这网站在线播放清晰度有720p

**Comment by panh0316** [comment]
试过看山寨小盟主这部电视剧，比软件里的所有资源都清晰

**Comment by Hunlongyu** [comment]
抱歉哦~ 
影视网 和 资源网 性质还是不一样的.
资源网格式相对统一, 可以用最少的代码, 解析最多的资源.
而且, 目前我加班严重, 没有精力适配,影视网.

**Comment by panh0316** [comment]
好的，好好休息最重要，老哥保重身体啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hunlongyu"<notifications@github.com&gt;; 
发送时间: 2020年5月29日(星期五) 上午9:25
收件人: "Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;; 
抄送: "987220406"<987220406@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Hunlongyu/ZY-Player] 建议增加一个资源网站 (#43)





 
抱歉哦~
 影视网 和 资源网 性质还是不一样的.
 资源网格式相对统一, 可以用最少的代码, 解析最多的资源.
 而且, 目前我加班严重, 没有精力适配,影视网.

**Comment by Hunlongyu** [comment]
😄
