### ISSUE TITLE
electron项目能编译到armbian上用么?

### ISSUE THREAD

**Issue by diyism** [Hunlongyu/ZY-Player#44]
electron项目能编译到armbian上用么?
要是能把zy-player编译到armbian上就好了,
那样很多便宜的单板机都可以不用装android直接装armbian加上zy-player就可以插到电视上看了

**Comment by Hunlongyu** [comment]
咳咳~
我只是一个小前端啦~
这个超出我的能力了, 关键加班严重, 我还没有时间去了解这些东西.

**Comment by diyism** [comment]
https://www.electron.build/cli
看起来 只要在build参数 --mac  --linux --win 后 再加 --arm64 就能 多生成一个给 树莓派 或 松果派 里ubuntu/debian arm64 使用的版本了

**Comment by Hunlongyu** [comment]
额~ 如果是 appImage 后缀的安装包, 我这边默认打包就有呀.
