### ISSUE TITLE
建议能自定义源，给出模板

### ISSUE THREAD

**Issue by lengyihan7** [Hunlongyu/ZY-Player#45]
如题，自带的源画质不是太好。

**Comment by Hunlongyu** [comment]
src/lib/site 下的两个文件,一个是网站数据, 一个是解析工具.
目前爬取的网站, 格式相对统一, 即用最少的代码, 解析最多的网站.
如果自定义的话, 网上那么多形形色色的网站.一个网站一套代码. 而且有的网站做了限制, 还不一定能播放成功.
总之,有能力的话, 可以自行尝试修改解析代码.
我这边加班严重, 没有太多精力做适配.
