### ISSUE TITLE
mac版本发现关闭后,后台还是继续在运行

### ISSUE THREAD

**Issue by huang159090** [Hunlongyu/ZY-Player#48]
首先感谢作者的辛勤开发,目前发现mac版本关闭后存在后台还是继续在运行的情况,期待能解决这个问题,做到真正的完全关闭.

**Comment by tim-hub** [comment]
是否有监测流量目的IP？

**Comment by Hunlongyu** [comment]
我是在 Win10 上开发的, 所以并不清楚 Mac 的运行状态, 周围也没有 Mac 电脑
关键是最近一直加班, 没有精力解决
不过我会记下的

**Comment by huang159090** [comment]
谢谢你的辛苦开发  支持你 可以搞个黑苹果玩玩也是不错的

**Comment by Hunlongyu** [comment]
@huang159090 
最新版已经解决无法完全退出的情况， 欢迎升级体验哦~😋
