### ISSUE TITLE
运行过程中经常出现Javascript报错

### ISSUE THREAD

**Issue by taozee** [Hunlongyu/ZY-Player#5]
![image](https://user-images.githubusercontent.com/61226276/74815464-3c1a9000-5334-11ea-99d7-22fdc04b432d.png)
如图ZY Player在运行过程中经常会有 a javascript error occurred in the main process 的报错 传统解决方法无法解决 清理软件缓存也无法解决 请设计者考虑此问题进下版本更新，谢谢

**Comment by Hunlongyu** [comment]
报错的原因：可能是因为网络无法链接github，导致无法获取到更新，而运行错误。我会尝试修复这个bug。

**Comment by Hunlongyu** [comment]
目前筹划新版本, 计划在下一个版本解决.
