### ISSUE TITLE
1.0.13 集数完全反

### ISSUE THREAD

**Issue by FreeGAV** [Hunlongyu/ZY-Player#50]
1.0.13 集数完全反了  最新的剧集被标识成第一集

**Comment by Hunlongyu** [comment]
请问哪一个 资源网么? 我这边没有发现

**Comment by FreeGAV** [comment]
1.0.13-1.0.14几个资源站都存在此问题
- [ 比如搜索 秋蝉  播放，  直接浏览器播放没这个问题。 ] 
- [1.0.14 又多了一个问题，同一电视剧，不同资源站切换后  点击播放不跳转还是原先资源站的 ]
