### ISSUE TITLE
1.0.13版bug，标识集数和实际集数不符。

### ISSUE THREAD

**Issue by linandoo** [Hunlongyu/ZY-Player#51]
集数顺序全部错乱。

**Comment by Hunlongyu** [comment]
请问是所有的资源网都乱序么?还是个别的?我这边调试没有发现呢

**Comment by linandoo** [comment]
试了几个资源网都有这种情况，在右侧剧集列表手动切换剧集后会出现错乱。
另外除了这个问题1.0.14版新增无法跳转播放资源的问题，即我现在在看节目A，中途想看节目B，搜索节目B点击播放后播放器无反应，还是原先节目A的画面不跳转。
