### ISSUE TITLE
版本1.0.15 无法加载内容？

### ISSUE THREAD

**Issue by Jones-Zachary-hi** [Hunlongyu/ZY-Player#58]
windows端安装后，一直在加载，所有网站均无法加载出内容

**Comment by Hunlongyu** [comment]
我这边所有网站的资源都可以加载出来的, 你用的什么网络么?移动?电信?

尝试点击 浏览列表下方的 [加载不出来,点这里] . 看看 网站能不能打开, 如果打不开, 就不是软件问题. 如果打开了, 切回软件, 重新选择该资源网. 一般就能加载出内容了.

**Comment by Jones-Zachary-hi** [comment]
> 我这边所有网站的资源都可以加载出来的, 你用的什么网络么?移动?电信?
> 
> 尝试点击 浏览列表下方的 [加载不出来,点这里] . 看看 网站能不能打开, 如果打不开, 就不是软件问题. 如果打开了, 切回软件, 重新选择该资源网. 一般就能加载出内容了.

您好，我这边网站可以打开，可是切回软件还是加载不出来
我换了一个版本的软件尝试了一下，也是一样的

**Comment by Hunlongyu** [comment]
@Jones-Zachary-hi 
打开网站后, 切回软件, 需要再次点击加载, 软件并不会自动加载, 因为获取不到你浏览器的状态.

即:  内容无法加载 -> 点击下方无法加载 -> 浏览器打开网站 -> 如果浏览器能打开 -> 切回软件 -> 选择分类重新加载 -> ok

**Comment by Hunlongyu** [comment]
还有就是有时资源可以加载出来, 但是视频无法播放. 
那是因为: 
1. 资源列表  和  视频资源  是两个东西.
2. 能加载资源列表不代表一定能播放视频.
3. 所以添加了很多资源网, 就是来回切换使用.
4. 如果那个网站很稳定, 可以设置里设置成默认网站.
