### ISSUE TITLE
这个页面能不能设置一个收藏按钮？

### ISSUE THREAD

**Issue by klxq520** [Hunlongyu/ZY-Player#59]
![QQ截图20200531212032](https://user-images.githubusercontent.com/45682501/83353397-ef0f7680-a384-11ea-9303-7e610c38bfc2.png)

就是搜索到资源后点进去看详情的时候，可以顺手收藏哈，不用叉掉出来收藏

**Comment by FreeGAV** [comment]
只有播放界面可收藏

**Comment by Hunlongyu** [comment]
可以考虑, 未来某个版本会加上~

**Comment by Hunlongyu** [comment]
最新正式版: v2.x 已加入该功能. 欢迎体验尝试哦~
