### ISSUE TITLE
卡卡卡

### ISSUE THREAD

**Issue by arthur1976** [Hunlongyu/ZY-Player#594]
**描述错误**
清楚简洁地说明错误是什么。
最近看什么片都很卡啊 切换源也是如此。。。我最近在看大秦赋   你可以试试看卡不卡。。。
**重现**
重现行为的步骤

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 19042.685]
  -软件安装包及版本：[例如：Windows 64位绿色版 2.6]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by buvta** [comment]
没问题，可能偶有卡顿但还是能看，请确保软件是最新版，没有启用代理
