### ISSUE TITLE
软件安装问题 ！！！

### ISSUE THREAD

**Issue by lanlan1234** [Hunlongyu/ZY-Player#6]
1.在安装时电脑windows安全中心会判定为带病毒直接删除。
2.安装时不能手动进行选择路径。
希望能够得到改善一下吧！

**Comment by Hunlongyu** [comment]
1. 因为没有windows证书，所以会被判定不安全。证书太贵啦，软件本身免费，不可能花大价钱去买证书。
2. 从 v0.8.19 版本开始，已经可以手动选择安装路径了。

**Comment by lanlan1234** [comment]
好的，
