### ISSUE TITLE
2.7版本搜索后页面空白

### ISSUE THREAD

**Issue by xxx975** [Hunlongyu/ZY-Player#600]
2.7版本怎么搜索不到美剧了.

**Comment by buvta** [comment]
是不是开启过滤了，隐藏工具栏再试下

**Comment by pzl0708** [comment]
我的什么剧都搜不到

**Comment by buvta** [comment]
请截图

**Comment by pzl0708** [comment]
> 请截图

![QQ图片20201225104654](https://user-images.githubusercontent.com/45899342/103115890-42d60a00-469f-11eb-8e8a-dcf30025ad4d.png)

**Comment by buvta** [comment]
切换下视图模式

推测是从较旧版本升级上来的，数据库不全所致，如果还存在问题请重置软件

**Comment by pzl0708** [comment]
切换视图模式后正常显示
