### ISSUE TITLE
为什么卸载后再安装仍有之前的文件

### ISSUE THREAD

**Issue by NamelessJohan** [Hunlongyu/ZY-Player#602]
Mac版本，卸载最近几个版本后，重新安装，不需要备份或者手动添加，之前添加过的播放源和收藏的电影都能自动显示。这软件有自动备份功能吗，备份到了哪里？还是说我无法卸载干净。

**Comment by NamelessJohan** [comment]
还有一点，2.7.0mac安装后打不开，显示a javascript occurred in the main process

**Comment by buvta** [comment]
数据文件夹请路径可参考相应系统下chrome的配置文件夹路径，请善用搜索

~/Library/Application Support下zy

#593
