### ISSUE TITLE
跳过片尾的问题

### ISSUE THREAD

**Issue by beyond7100** [Hunlongyu/ZY-Player#606]
**描述错误**
正常播放到片尾的时间会自动跳过片尾，但是如果快进5秒快进5秒这种形式到片尾时间就不会自动跳过，可能是到了片尾指定的时间才会跳过片尾，建议设置成播放剩余时间小于片尾时间就直接跳过片尾播放下一集

**环境：**
Mac

**Comment by buvta** [comment]
这样会导致无法通过快捷键调整片尾标记
