### ISSUE TITLE
直接集成电视系统，卖电视/投影仪吧

### ISSUE THREAD

**Issue by omoxop** [Hunlongyu/ZY-Player#608]
不用安卓TV版了，做个系统，把现有的电视全刷了

**Comment by lighterEB** [comment]
> 不用安卓TV版了，做个系统，把现有的电视全刷了

版权了解一下，您这是诱导别人犯罪吗

**Comment by omoxop** [comment]
> > 不用安卓TV版了，做个系统，把现有的电视全刷了
> 
> 版权了解一下，您这是诱导别人犯罪吗

法律法规了解下，搜索引擎
