### ISSUE TITLE
速度明显降低

### ISSUE THREAD

**Issue by iPartTao** [Hunlongyu/ZY-Player#609]
我是从2.6.5开始用的，从2.6.8开始，速度就比之前慢太多了，以前从来没卡过，现在开始一集就得先缓冲2分钟再看才行。麻烦优化一下。Win7x64，16G内存，固态，联通内部独享300M光纤，家里普联POE企业级路由器，网速绝对没问题。

**Comment by buvta** [comment]
请到设置确认下有无设置代理
