### ISSUE TITLE
Win7 64位打开无法显示主界面

### ISSUE THREAD

**Issue by long13117** [Hunlongyu/ZY-Player#61]
只在任务栏显示但是无法打开主界面

**Comment by Hunlongyu** [comment]
是不是打开的时候, 界面跑到屏幕外面去了,

百度搜索关键句: 
1. Win7 软件在屏幕外

参考教程: 
1. http://www.sys321.com/9231.html
2. https://wenku.baidu.com/view/f4249505ba1aa8114431d9fe.html

**Comment by long13117** [comment]
试过并非这里的问题，后来尝试在属性-兼容性里勾选“以管理员身份运行”解决问题
