### ISSUE TITLE
新年版播放源和直播源全部消失

### ISSUE THREAD

**Issue by kugoo** [Hunlongyu/ZY-Player#614]
新年版播放源和直播源全部消失，重置后还是没有

**Comment by tzvecqian** [comment]
一样

**Comment by buvta** [comment]
是Mac吗？更新下载完毕后有没有点过“安装”？

请到设置确认下版本，如果版本无误请备份好历史与收藏后重置软件

**Comment by 15531700396** [comment]
一样出现此情况 win10 2004

**Comment by buvta** [comment]
如果是比较老旧的版本，请先升级到v2.7.0导入历史与收藏后，再安装最新版

**Comment by ConcealedBlade** [comment]
认真看https://github.com/Hunlongyu/ZY-Player/issues/80

9. 安装新版本后不工作/部分功能不正常
数据文件夹位置可参考相应系统下chrome的配置文件夹路径
Windows下,请清理 AppData\Roaming\zy文件夹
linux下，请清理~/.config/zy
MacOS下，请清理Users/用户名/Library/Application Support/zy
MacOS更新报错，重新安装打不开A JavaScript error occurred in the main process请参考 #593
清理后重置软件，再重试.
安装新版后部分功能不正常也可以按上述操作，如果还是不行请报bug

清理后问题解决

**Comment by buvta** [comment]
需要保留数据，请看新版日志
