### ISSUE TITLE
串音串画

### ISSUE THREAD

**Issue by DarrenSong** [Hunlongyu/ZY-Player#615]
**描述错误**
播放一个视频的时候，有时候画面卡住，会有其他视频的声音，有时候会有其他视频的画面

**重现**
正常播放

**预期行为**
串画

**截图**

**环境：**
  -操作系统及版本：Windows 10 64位  19041.685
  -软件安装包及版本：v2.7.0

**Comment by buvta** [comment]
截图不适，已删除

**Comment by buvta** [comment]
会不会是源的缘故，之前在群里看到有人遇到过此类现象

**Comment by huangyucheng0** [comment]
我的也是，只有声音在播放，画面定格

**Comment by DarrenSong** [comment]
解决了？

**Comment by buvta** [comment]
请换源，很可能是视频源的问题
