### ISSUE TITLE
请求在播放换源的界面 添加一个名称过滤✍

### ISSUE THREAD

**Issue by Louis209** [Hunlongyu/ZY-Player#619]
请求在播放换源的界面 添加一个名称过滤
——————————————————
追剧时换源会有 和视频名称不符的片

请大大看图
https://s3.ax1x.com/2021/01/03/s9i5od.png
尤其是添加的源多了的时候 删掉或关闭又不忍心

**Comment by buvta** [comment]
请忽略或关掉123资源及1717云资源的搜索结果，这两个源现在搜索结果返回异常
