### ISSUE TITLE
win10v20h2上开始菜单磁贴是灰色的，正常软件应该是白色

### ISSUE THREAD

**Issue by cutebabyzhi** [Hunlongyu/ZY-Player#620]
**描述错误**
win10v20h2上开始菜单磁贴是灰色的，正常的软件应该是白色磁贴

**重现**
常态问题

**预期行为**
白色开始菜单磁贴图标

**截图**

![C%Y51@L9${9 0UE8R_U(O$X](https://user-images.githubusercontent.com/61002577/103496495-66f0d280-4e79-11eb-8d5a-4985ad3ecba7.png)

**环境：**
  -操作系统及版本：Windows 10 64位 20h2
  -软件安装包及版本：zy最新版

**Comment by 15531700396** [comment]
我这也是灰的20H2 正常啊
弄一下主题设置试试

**Comment by buvta** [comment]
请自行搜索磁贴异色

**Comment by cutebabyzhi** [comment]
> 请自行搜索磁贴异色

啥呀？五颜六色磁贴是之前的样式，现在最新版开始菜单统一是透明模糊效果的
