### ISSUE TITLE
（未回答的问题请删除，减少多余信息干扰）

### ISSUE THREAD

**Issue by wxid7180a** [Hunlongyu/ZY-Player#624]
**描述错误**
影视推荐内容模块，更新推荐时，出现
![捕获](https://user-images.githubusercontent.com/28597328/104406424-39530a00-559a-11eb-821b-c70881aaa1f6.PNG)

环境：
  -操作系统及版本：win10 64位
  -软件安装包及版本：V2.7.1

**Comment by cuiocean** [comment]
正如提示所说,你的网络无法直接访问Github上的文件.你要么使用代理,要么等待内置的推荐更新.
