### ISSUE TITLE
更新7.2.7版本后，影视资源信息清空，且无法添加

### ISSUE THREAD

**Issue by littleseven23** [Hunlongyu/ZY-Player#627]
![360截图20210122182831242](https://user-images.githubusercontent.com/77834799/105479726-c9522b80-5cdf-11eb-82ee-b82fa60a29dc.jpg)
如图，更新后找不到资源站了，请问如何解决 ？直播资源也是一片空白，怎么添加？
添加后无法验证是什么原因？

**Comment by buvta** [comment]
请重置软件
