### ISSUE TITLE
PC端播放黑屏

### ISSUE THREAD

**Issue by liuxuehu65** [Hunlongyu/ZY-Player#628]
v2.61 版本、系统win10

问题：PC端播放有声音，
![反馈](https://user-images.githubusercontent.com/50710446/105481488-1505d480-5ce2-11eb-8f03-9a37fbc3d69c.jpg)
无画面

**Comment by buvta** [comment]
请用最新版尝试下

**Comment by liuxuehu65** [comment]
最新版也装了，还是同样的问题，但是WIN7系统下是正常的。 hal liu 邮箱：liubingshu0129@gmail.com 签名由 网易邮箱大师 定制 在2021年01月22日 19:27，buvta 写道： 请用最新版尝试下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by liuxuehu65** [comment]
hal liu 邮箱：liubingshu0129@gmail.com 签名由 网易邮箱大师 定制 在2021年01月22日 19:27，buvta 写道： 请用最新版尝试下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by buvta** [comment]
不同源直播点播时都黑屏？win10下之前有用过其它版本吗？能否正常播放？
点击调试获取视频链接复制到web版试下

**Comment by liuxuehu65** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    

    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        1. 不同的直播源都是黑屏有声音
        2.其它的版本都是一样，不能播放3.切换到kkyun就闪一下图像4. 操作系统	Windows 10 OS Version 1909 (Build 18363.1256)
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liubingshu0129
                            
                    
                        
                            
                                    liubingshu0129@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年1月22日 22:59，buvta<notifications@github.com> 写道： 




不同源直播点播时都黑屏？win10下之前有用过其它版本吗？能否正常播放？

点击调试获取视频链接复制到web版试下



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by buvta** [comment]
请用最新版，参考以下步骤：
1. 参照常见问题清除数据文件夹并重置软件
2. 参考最新版日志黑屏操作
3. 多试几个源，选择非m3u8的播放列表尝试下能否正常播放
4. 选择m3u8播放列表，点击播放器下方调用第三方播放器(先不要设置第三方播放器，以调用web版接口)
