### ISSUE TITLE
win7 32位系统无法正常安装的问题

### ISSUE THREAD

**Issue by zhx12138** [Hunlongyu/ZY-Player#63]
你好，大神，由于我对于编程啥的不是很懂，所以我也不知道是为啥出现了这个问题。

我描述一下我的问题，我是win7的32位系统，但是今天我尝试了无论是64还是32位的软件都无法正常安装，32位的时候提示与我目前正在使用的系统不兼容。。。最新的1.0.16版本也无法正常安装。

最后祝大神六一快乐

**Comment by Hunlongyu** [comment]
@zhx12138 

我没有 32位 系统, 也懒得装虚拟机了. 
你加我微信: hunlongyu
我发你安装包, 你帮我测试一下可以么?

**Comment by Hunlongyu** [comment]
我这边通过其他方式, 貌似弄好了, 但是没有校验能不能安装成功. 
可以的话, 希望帮忙测试一下哈~
地址: https://www.lanzous.com/b04s6a3re
密码: 95px
蓝奏云网盘里是最新版, 包含了 32位 安装包

**Comment by zhx12138** [comment]
好好，不好意思，才看到邮件，非常抱歉，麻烦大佬了。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 晚上6:14
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"5贪得厌"<604469940@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] win7 32位系统无法正常安装的问题 (#63)





 
我这边通过其他方式, 貌似弄好了, 但是没有校验能不能安装成功.
 可以的话, 希望帮忙测试一下哈~
 地址: https://www.lanzous.com/b04s6a3re
 密码: 95px
 蓝奏云网盘里是最新版, 包含了 32位 安装包

**Comment by zhx12138** [comment]
大佬，已经可以正常安装了，再次感谢您，谢谢谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hunlongyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 晚上6:14
收件人:&nbsp;"Hunlongyu/ZY-Player"<ZY-Player@noreply.github.com&gt;;
抄送:&nbsp;"5贪得厌"<604469940@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Hunlongyu/ZY-Player] win7 32位系统无法正常安装的问题 (#63)





 
我这边通过其他方式, 貌似弄好了, 但是没有校验能不能安装成功.
 可以的话, 希望帮忙测试一下哈~
 地址: https://www.lanzous.com/b04s6a3re
 密码: 95px
 蓝奏云网盘里是最新版, 包含了 32位 安装包
