### ISSUE TITLE
您没有权限来打开应用程序“ZY Player.app”。

### ISSUE THREAD

**Issue by vbonluk** [Hunlongyu/ZY-Player#630]
**描述错误**
清楚简洁地说明错误是什么。

Mac Big Sur最新版无法打开提示：

您没有权限来打开应用程序“ZY Player.app”。

![image](https://user-images.githubusercontent.com/7578155/105566724-a6b82500-5d68-11eb-8cd9-68587afd65de.png)

已经查过百度，使用upx来修复，接着还是失败提示：

 not packed by UPX

![image](https://user-images.githubusercontent.com/7578155/105566757-d0714c00-5d68-11eb-9fec-fbe98c3ca11b.png)

**重现**
重现行为的步骤

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by buvta** [comment]
https://blog.csdn.net/airconan/article/details/112692057
https://www.zhihu.com/question/431722091

**Comment by vbonluk** [comment]
@buvta 也尝试过这个方法，依然不行。

**Comment by vbonluk** [comment]
@buvta 
![image](https://user-images.githubusercontent.com/7578155/105570527-f0166d80-5d84-11eb-94a9-04078b5a8086.png)

**Comment by buvta** [comment]
加执行权限 sudo chmod -r a+x ZY\ Player

**Comment by vbonluk** [comment]
![image](https://user-images.githubusercontent.com/7578155/105570958-5bf9d580-5d87-11eb-87d9-24f8c5466fe2.png)

我原本是用zip包解压的，现在换成dmg包安装可以用了。
