### ISSUE TITLE
搜索结果不准确

### ISSUE THREAD

**Issue by FlyingDragon0420** [Hunlongyu/ZY-Player#632]
**描述错误**
搜索结果不准确

**重现**
搜索 青春有你2

**预期行为**
搜索内容全部和搜索内容相关

**截图**
![捕获](https://user-images.githubusercontent.com/41459054/105631889-a82e3e00-5e8b-11eb-8518-44e081e47dab.PNG)

**环境：**
Windows 10 64位 19042.782
Release 2.7.2

**Comment by buvta** [comment]
把123资源和1717云资源关掉，这两个源搜索结果返回异常

**Comment by buvta** [comment]
已优化搜索，请等待新版发布
