### ISSUE TITLE
蓝奏云网盘里的还是 2.6.1 老版本，该更新啦！

### ISSUE THREAD

**Issue by XIU2** [Hunlongyu/ZY-Player#634]
鉴于 Github Release 下载速度比较捉急，而软件安装包体积较大，还是**很多人需要蓝奏云**来下载的。

但是我发现蓝奏云网盘中的文件还是 **2.6.1 老版本**，该更新啦！

https://www.lanzoux.com/b04s6a3re
密码:95px

**Comment by Hunlongyu** [comment]
已经更新到最新版本了.
