### ISSUE TITLE
能不能让用户自己添加新的资源站和带有封面的资源显示

### ISSUE THREAD

**Issue by kmzzl** [Hunlongyu/ZY-Player#66]
根据现有规则，让用户在软件里自己添加资源站，同时希望增加一个带有影视海报的模板（有些电视名字一样，但是年代不一样）和缓存下载

**Comment by Hunlongyu** [comment]
1. 不能自定义添加资源站, 基本上,一个网站一套解析代码.
2. 海报模式可以实现, 但是不建议. 主要是海报模式会一次性请求过多, 容易被网站屏蔽.
3. 视频源 是 m3u8 格式的, 无法缓存下载, 且 m3u8 下载也需要专门的工具下载. 只有部分网站下载链接是 MP4 的.
