### ISSUE TITLE
可否加个检查更新的按钮？

### ISSUE THREAD

**Issue by why2785** [Hunlongyu/ZY-Player#67]
1、如题，可否加个检查更新的按钮？
2、另外，win版本的最小化和关闭按钮仿MAC风格，不易识别，容易误触。
3、当界面精简模式后，无法返回完整模式，建议增加返回完整模式按钮。

**Comment by Hunlongyu** [comment]
1. 每次启动软件会自动查询更新,并后台自动下载文件, 关闭软件后, 自动安装. 所以并不太需要检查更新功能按钮.
2. 因为软件跨平台, 所以按钮没有使用 win 风格, 而且这个按钮使用一两次就熟悉了吧.
3. 直接关闭精简模式, 就可以返回完整模式. 不过由于设计缺陷, 没法返回之前的状态. 这个未来有时间了, 我会修复的.
