### ISSUE TITLE
Android 版本可否考虑

### ISSUE THREAD

**Issue by ArtistZhou** [Hunlongyu/ZY-Player#68]
目前大部分人都用手机投屏电视看剧，既然楼主用的是跨平台的electron，是否考虑优先搞一个Android版本。应该会方便很多。就是不清楚是否有法律方面的问题。毕竟人人视频也没有电视版的。希望卤煮可以考虑一下。

**Comment by Hunlongyu** [comment]
有考虑， 不过短期内完不成， 最近忙于公司项目， 一直加班， 累到快吐血
