### ISSUE TITLE
安装程序未能成功地运行完成

### ISSUE THREAD

**Issue by freeleefly** [Hunlongyu/ZY-Player#69]
0.8.9 的时候下载 setup.exe 文件安装的，然后都是自动更新，也没怎么使用。
然后今天白天在微博上看到更新了，说是支持下载，想起来点开试试看。自动更新，显示1.0.14 然后有提示更新，重启到1.0.17了。发现界面换了，然后原来的收藏的记录也不见了。
然后在 "C:\Users\用户\AppData\Local\Programs\" 目录下有两个 文件夹"ZY Player"、"zy"，不同版本的，zy下的，进去，还有一排tab “福利”什么的。
然后安装位置不是我习惯的位置，就想删了重启，反正原来的记录也不见了。手一滑，直接文件夹删除了，两个都。
然后再下载安装文件，再也安装不成功了。不管是单个用户还是所有用户，均提示“安装程序未能成功地运行完成”
用0.8.9的安装文件，也一直再刷进度条。
请问有没有什么办法重新安装。

**Comment by freeleefly** [comment]
用IObit Uninstaller看到了，卸载一边，再安装可以看到了，但是安装时候，还是能检测并提示我已经有一个安装目录了，有点难受。

**Comment by Hunlongyu** [comment]
抱歉照成困扰。😅
2个版本跨度较大，一些命名细节忘了，照成不同版本， 不同目录。😂
