### ISSUE TITLE
Win10 2004 预览版无法打开

### ISSUE THREAD

**Issue by XuCpeng** [Hunlongyu/ZY-Player#73]
Win 10 2004 预览版 64位
操作系统版本	10.0.19635.1

ZY-Player 1.0.17 无法打开，双击无反应

**Comment by walker4753** [comment]
同版本无法打开

**Comment by winlans** [comment]
我的倒是可以打开， 但是播放是一帧一帧的播放。。。。
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19041 暂缺 Build 19041

ZY-Player 1.0.18

**Comment by 953521910** [comment]
同win10,2004版本，用的64位应用，打不开，安装了1.0.16，1.0.18都打不开@Hunlongyu

**Comment by Hunlongyu** [comment]
我自己用的两台电脑分别是：
Win10 1909 18363.836
Win10 2004 19577.1000
都是 64 位，均可以正常运行。
尝试使用 兼容模式启动，如果不行的话，我暂时也不知道怎么解决。

**Comment by AzlmZ-del** [comment]
亲测”以兼容模式运行“可解决问题

**Comment by 953521910** [comment]
> 我自己用的两台电脑分别是：
> 
> ```
> Win10 1909 18363.836
> Win10 2004 19577.1000
> ```
> 
> 都是 64 位，均可以正常运行。
> 
> 1. 尝试 从 GitHub 网站下载最新版安装运行
> 2. 尝试使用 兼容模式启动
> 
> > 如果不行的话，我暂时也不知道怎么解决。


> 我自己用的两台电脑分别是：
> 
> ```
> Win10 1909 18363.836
> Win10 2004 19577.1000
> ```
> 
> 都是 64 位，均可以正常运行。
> 
> 1. 尝试 从 GitHub 网站下载最新版安装运行
> 2. 尝试使用 兼容模式启动
> 
> > 如果不行的话，我暂时也不知道怎么解决。

兼容模式运行好用了，感谢

**Comment by Hunlongyu** [comment]
最新正式版: v2.x 已发布, 欢迎体验.
