### ISSUE TITLE
m1 macbook pro 无法安装？

### ISSUE THREAD

**Issue by mtcoafun** [Hunlongyu/ZY-Player#766]
### 最新版、安装方式、系统

1. 你在使用什么版本的
最新版
2. 你通过什么方式安装
dmg 和 zip
3. 你所使用的操作系统
m1 pro MacBook Pro

### 描述问题：

两种包下载都失败了，显示无法验证 app 安全性

**Comment by anaer** [comment]
“系统偏好设置”——> “安全性与隐私 ”——> “通用”——>“仍要打开” ？

**Comment by mtcoafun** [comment]
我试试

**Comment by mtcoafun** [comment]
打开了，感谢
