### ISSUE TITLE
请教下CMS类的资源站是否只能1次获取最多20个对象？

### ISSUE THREAD

**Issue by dbsxdbsx** [Hunlongyu/ZY-Player#803]
我搜了几个资源站，好像基本都是：
```
列表接收参数：
ac=list
t=类别ID
pg=页码
wd=搜索关键字
h=几小时内的数据
...
```
返回的json中的limit都是20，那是否意味着没有办法一次性请求返回超过20个？

（我看了下 本项目中`tools.js`的代码，貌似也没有相应的处理。 若是我漏看了烦请指正）

**Comment by Hiram-Wong** [comment]
我看了一下苹果 cms和版本有关，最新几个版本支持 pagesize 参数

**Comment by dbsxdbsx** [comment]
> 我看了一下苹果 cms和版本有关，最新几个版本支持 pagesize 参数

是否很多cms站点都会遵行苹果cms的协议？ 如果是的话，那也许过一段时间这些cms站点就可以通过他们提供的api加上pagesize参数取数据了吧。

**Comment by Hiram-Wong** [comment]
> 应该是的 毕竟这么多站要采集，但我测试了好几个资源站都没更新，估计都停留在很久之前了

**Comment by dbsxdbsx** [comment]
感谢回复。我觉得可能不更新的一个原因是若用户一次性采集了pagesize太大，会影响cms站点服务器的运行效率吧。
