### ISSUE TITLE
播放快捷键

### ISSUE THREAD

**Issue by qiuxiang1978** [Hunlongyu/ZY-Player#85]
1：建议把播放快捷键 比如：上一集 下一集 播放列表 等等 做到播放界面里 不要在播放界面外面的页面里
2：音量大小调节后不会储存 每一次开软件 音量都要重新调节过
3：影片清晰度太低，不说1080P，连360P估计都够呛吧，这样会少了很大一波有需求的忠实粉丝的，至少可以有1080 720这样清晰度的选项，这样画质与速度都兼顾
4：强烈建议开发电视和手机app，这个是趋势
希望ZY Player越来越好！！！

**Comment by Hunlongyu** [comment]
最新正式版: v2.x 已发布, 欢迎体验.

1. 快捷键目前只在 播放界面生效
2. 音量没有做记录. 你可以尝试修改电脑音量
3. 资源来自网络, zy 不提供任何资源哦. 尝试切换源 找一找 有高清资源的视频.
4. 手机 app, 已经有人开发了.
