### ISSUE TITLE
zyplayer经常无故被一个程序卸载

### ISSUE THREAD

**Issue by freetitan** [Hunlongyu/ZY-Player#89]
你好，最近几天使用在win10下使用zyplayer，每次软件关闭之后，会出现一个来自未知发布者的old uninstaller程序申请权限，如果同意，zy的整个安装目录就会被完全删除，试了内部测试版与最新版，都一样，不知道这是一种什么程序，怎么才能彻底消除？

谢谢！

**Comment by Hunlongyu** [comment]
不清楚... zy 代码开源, 没有后门, 也没有恶意代码. 前提是从这里下载安装的,不是别人二次打包的.
你是不是安装了卡巴斯基等杀毒软件. 或者什么安全卫士?尝试加入白名单.
