### ISSUE TITLE
是否准备支持win32 86

### ISSUE THREAD

**Issue by Roadmanteacher** [Hunlongyu/ZY-Player#9]
现在只是支持win64，什么时候支持win32

**Comment by Hunlongyu** [comment]
由于复工, 该项目目前处于停滞状态.
推荐 32 位系统的使用该油猴插件: https://greasyfork.org/zh-CN/scripts/383642-%E5%B0%8F%E5%8A%A9%E6%89%8B-%E8%B5%84%E6%BA%90%E5%8A%A9%E6%89%8B
都是本人开发, 不受系统限制.
