### ISSUE TITLE
界面自适应

### ISSUE THREAD

**Issue by WinterSoHot** [Hunlongyu/ZY-Player#90]
当我使用AppImage时候，在看视频时，最大化窗口的时候，界面并不会相应的自适应变化。
![Screenshot from 2020-06-09 11-21-53](https://user-images.githubusercontent.com/19640280/84102575-732bc300-aa43-11ea-9c50-4a4b2bcca62f.png)

**Comment by Hunlongyu** [comment]
有兴趣一起开发小东西嘛?
有兴趣的话, 加微信交流一下?
微信号: hunlongyu
