### ISSUE TITLE
同道中人呀，交流交流？

### ISSUE THREAD

**Issue by fly1397** [Hunlongyu/ZY-Player#91]
去年搞了一个跟这个差不多的app
也是集合了多种资源来做的，用的react + antd + umi
功能进度上优先一点，资源添加，投屏，局域网访问等。
交流交流？

**Comment by Hunlongyu** [comment]
😃 好呀~
加微信交流交流~
微信号: Hunlongyu

**Comment by xu93nuo1987** [comment]
大神些快交流，出APP

**Comment by xu93nuo1987** [comment]
大神些快交流，出APP

**Comment by vicedev** [comment]
> 大神些快交流，出APP

[ZY-Player-Android](https://github.com/vicedev/ZY-Player-Android)，可以看下我做的这个Android版本~
