### ISSUE TITLE
作者你好，播放器能否添加调节视频清澈度和视频跳过片头片尾啊？

### ISSUE THREAD

**Issue by 18206569251** [Hunlongyu/ZY-Player#92]
作者你好，播放器能否添加调节视频清澈度和视频跳过片头片尾啊？其实播放器已经很好很强大了，就是在加上这些功能就更好了

**Comment by 18206569251** [comment]
> 作者你好，就是在加入客户登录就好了，每次一重装系统了，收藏的电影和电视剧都没有了

**Comment by Hunlongyu** [comment]
1. 不行哦~ 视频源 是从网上爬取的, 资源是别人的. 清晰度别人说了算, 我只是视频的搬运工, 额外添加一点功能罢了. 
2. 记录收藏的功能需要一台服务器, 软件是免费使用的, 并没有收入. 购买服务器, 对大负翁来说, 雪上加霜呢.
😂
