### ISSUE TITLE
基于作者的项目做了一个Android手机版本的

### ISSUE THREAD

**Issue by vicedev** [Hunlongyu/ZY-Player#97]
基于作者的项目做了一个Android版本的，[ZY-Player-Android](https://github.com/vicedev/ZY-Player-Android)，想手机端看的朋友可以试下哦。后面有时间尝试用Flutter做手机端跨平台的。

**Comment by Hunlongyu** [comment]
哈哈, 厉害~🎉
我还在加班呢~ 真的是一点时间都没有~

**Comment by vicedev** [comment]
> 哈哈, 厉害~🎉 我还在加班呢, 真的是一点时间都没有~

这两天肝出来的O(∩_∩)O哈哈~

**Comment by Hunlongyu** [comment]
加个微信可以么?

**Comment by vicedev** [comment]
> 加个微信可以么?
> hunlongyu

加你啦~

**Comment by xu93nuo1987** [comment]
可惜不能投屏啊！

**Comment by Hunlongyu** [comment]
@xu93nuo1987 
慢慢来呀~ 敲代码费脑子, 给作者一点时间.

**Comment by vicedev** [comment]
> 可惜不能投屏啊！

现在功能还很简陋，后续会慢慢加的~

**Comment by iam3ddy** [comment]
会支持安卓TV吗？

**Comment by vicedev** [comment]
> 会支持安卓TV吗？

tv端的可能得交给其他开发去做~

**Comment by nickolboy** [comment]
谁来上个ios的
