### ISSUE TITLE
小窗模式

### ISSUE THREAD

**Issue by idootop** [Hunlongyu/ZY-Player#99]
当点击播放视频时，如果在视频尚未初始化之前打开小窗模式，主窗口和小窗模式视频会重叠播放，表现为会有两个视频声音略微重叠，此时程序会陷入死循环，无法关闭窗口。

**Comment by Hunlongyu** [comment]
最新正式版: v2.x 已发布, 欢迎体验.

新版的 Mini 模式已优化
